package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private Integer codigoArea;
     private Date version;
     private String nombreArea;
     private Set<Vendedor> vendedors = new HashSet<Vendedor>(0);

    public Area() {
    }

    public Area(String nombreArea, Set<Vendedor> vendedors) {
       this.nombreArea = nombreArea;
       this.vendedors = vendedors;
    }
   
    public Integer getCodigoArea() {
        return this.codigoArea;
    }
    
    public void setCodigoArea(Integer codigoArea) {
        this.codigoArea = codigoArea;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public String getNombreArea() {
        return this.nombreArea;
    }
    
    public void setNombreArea(String nombreArea) {
        this.nombreArea = nombreArea;
    }
    public Set<Vendedor> getVendedors() {
        return this.vendedors;
    }
    
    public void setVendedors(Set<Vendedor> vendedors) {
        this.vendedors = vendedors;
    }




}


