package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaEstadoUsuario generated by hbm2java
 */
public class AuditoriaEstadoUsuario  implements java.io.Serializable {


     private Integer codigoAudiEstadoUsuario;
     private String usuario;
     private Date fechaCambio;
     private String nombreEstadoUsuarioOld;
     private Date versionOld;
     private String nombreEstadoUsuarioNew;
     private Date versionNew;

    public AuditoriaEstadoUsuario() {
    }

	
    public AuditoriaEstadoUsuario(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaEstadoUsuario(String usuario, Date fechaCambio, String nombreEstadoUsuarioOld, Date versionOld, String nombreEstadoUsuarioNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreEstadoUsuarioOld = nombreEstadoUsuarioOld;
       this.versionOld = versionOld;
       this.nombreEstadoUsuarioNew = nombreEstadoUsuarioNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiEstadoUsuario() {
        return this.codigoAudiEstadoUsuario;
    }
    
    public void setCodigoAudiEstadoUsuario(Integer codigoAudiEstadoUsuario) {
        this.codigoAudiEstadoUsuario = codigoAudiEstadoUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreEstadoUsuarioOld() {
        return this.nombreEstadoUsuarioOld;
    }
    
    public void setNombreEstadoUsuarioOld(String nombreEstadoUsuarioOld) {
        this.nombreEstadoUsuarioOld = nombreEstadoUsuarioOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreEstadoUsuarioNew() {
        return this.nombreEstadoUsuarioNew;
    }
    
    public void setNombreEstadoUsuarioNew(String nombreEstadoUsuarioNew) {
        this.nombreEstadoUsuarioNew = nombreEstadoUsuarioNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


