package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaFacturaCTienePedido generated by hbm2java
 */
public class AuditoriaFacturaCTienePedido  implements java.io.Serializable {


     private Integer codigoAudiFacturaClienteTienePedido;
     private String usuario;
     private Date fechaCambio;
     private String nombreFacturaClienteTienePedidoOld;
     private String nombreFacturaClienteTienePedidoNew;

    public AuditoriaFacturaCTienePedido() {
    }

	
    public AuditoriaFacturaCTienePedido(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaFacturaCTienePedido(String usuario, Date fechaCambio, String nombreFacturaClienteTienePedidoOld, String nombreFacturaClienteTienePedidoNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreFacturaClienteTienePedidoOld = nombreFacturaClienteTienePedidoOld;
       this.nombreFacturaClienteTienePedidoNew = nombreFacturaClienteTienePedidoNew;
    }
   
    public Integer getCodigoAudiFacturaClienteTienePedido() {
        return this.codigoAudiFacturaClienteTienePedido;
    }
    
    public void setCodigoAudiFacturaClienteTienePedido(Integer codigoAudiFacturaClienteTienePedido) {
        this.codigoAudiFacturaClienteTienePedido = codigoAudiFacturaClienteTienePedido;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreFacturaClienteTienePedidoOld() {
        return this.nombreFacturaClienteTienePedidoOld;
    }
    
    public void setNombreFacturaClienteTienePedidoOld(String nombreFacturaClienteTienePedidoOld) {
        this.nombreFacturaClienteTienePedidoOld = nombreFacturaClienteTienePedidoOld;
    }
    public String getNombreFacturaClienteTienePedidoNew() {
        return this.nombreFacturaClienteTienePedidoNew;
    }
    
    public void setNombreFacturaClienteTienePedidoNew(String nombreFacturaClienteTienePedidoNew) {
        this.nombreFacturaClienteTienePedidoNew = nombreFacturaClienteTienePedidoNew;
    }




}


