package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudiClienteTienePreferencia generated by hbm2java
 */
public class AudiClienteTienePreferencia  implements java.io.Serializable {


     private Integer codigoAudiClienteTienePedido;
     private String usuario;
     private Date fechaCambio;
     private Integer fkcodigoClienteOld;
     private Integer fkcodigoProductoOld;
     private Date fechaVotoPreferenciaOld;
     private Integer cantidadPuntosOld;
     private Integer fkcodigoClienteNew;
     private Integer fkcodigoProductoNew;
     private Date fechaVotoPreferenciaNew;
     private Integer cantidadPuntosNew;

    public AudiClienteTienePreferencia() {
    }

	
    public AudiClienteTienePreferencia(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudiClienteTienePreferencia(String usuario, Date fechaCambio, Integer fkcodigoClienteOld, Integer fkcodigoProductoOld, Date fechaVotoPreferenciaOld, Integer cantidadPuntosOld, Integer fkcodigoClienteNew, Integer fkcodigoProductoNew, Date fechaVotoPreferenciaNew, Integer cantidadPuntosNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.fkcodigoClienteOld = fkcodigoClienteOld;
       this.fkcodigoProductoOld = fkcodigoProductoOld;
       this.fechaVotoPreferenciaOld = fechaVotoPreferenciaOld;
       this.cantidadPuntosOld = cantidadPuntosOld;
       this.fkcodigoClienteNew = fkcodigoClienteNew;
       this.fkcodigoProductoNew = fkcodigoProductoNew;
       this.fechaVotoPreferenciaNew = fechaVotoPreferenciaNew;
       this.cantidadPuntosNew = cantidadPuntosNew;
    }
   
    public Integer getCodigoAudiClienteTienePedido() {
        return this.codigoAudiClienteTienePedido;
    }
    
    public void setCodigoAudiClienteTienePedido(Integer codigoAudiClienteTienePedido) {
        this.codigoAudiClienteTienePedido = codigoAudiClienteTienePedido;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public Integer getFkcodigoClienteOld() {
        return this.fkcodigoClienteOld;
    }
    
    public void setFkcodigoClienteOld(Integer fkcodigoClienteOld) {
        this.fkcodigoClienteOld = fkcodigoClienteOld;
    }
    public Integer getFkcodigoProductoOld() {
        return this.fkcodigoProductoOld;
    }
    
    public void setFkcodigoProductoOld(Integer fkcodigoProductoOld) {
        this.fkcodigoProductoOld = fkcodigoProductoOld;
    }
    public Date getFechaVotoPreferenciaOld() {
        return this.fechaVotoPreferenciaOld;
    }
    
    public void setFechaVotoPreferenciaOld(Date fechaVotoPreferenciaOld) {
        this.fechaVotoPreferenciaOld = fechaVotoPreferenciaOld;
    }
    public Integer getCantidadPuntosOld() {
        return this.cantidadPuntosOld;
    }
    
    public void setCantidadPuntosOld(Integer cantidadPuntosOld) {
        this.cantidadPuntosOld = cantidadPuntosOld;
    }
    public Integer getFkcodigoClienteNew() {
        return this.fkcodigoClienteNew;
    }
    
    public void setFkcodigoClienteNew(Integer fkcodigoClienteNew) {
        this.fkcodigoClienteNew = fkcodigoClienteNew;
    }
    public Integer getFkcodigoProductoNew() {
        return this.fkcodigoProductoNew;
    }
    
    public void setFkcodigoProductoNew(Integer fkcodigoProductoNew) {
        this.fkcodigoProductoNew = fkcodigoProductoNew;
    }
    public Date getFechaVotoPreferenciaNew() {
        return this.fechaVotoPreferenciaNew;
    }
    
    public void setFechaVotoPreferenciaNew(Date fechaVotoPreferenciaNew) {
        this.fechaVotoPreferenciaNew = fechaVotoPreferenciaNew;
    }
    public Integer getCantidadPuntosNew() {
        return this.cantidadPuntosNew;
    }
    
    public void setCantidadPuntosNew(Integer cantidadPuntosNew) {
        this.cantidadPuntosNew = cantidadPuntosNew;
    }




}


