package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudiZonaTieneDistrito generated by hbm2java
 */
public class AudiZonaTieneDistrito  implements java.io.Serializable {


     private Integer codigoAudiZonaTieneDistrito;
     private String usuario;
     private Date fechaCambio;
     private Integer fkcodigoZonaOld;
     private Integer fkcodigoDistritoOld;
     private Date versionOld;
     private Integer fkcodigoZonaNew;
     private Integer fkcodigoDistritoNew;
     private Date versionNew;

    public AudiZonaTieneDistrito() {
    }

	
    public AudiZonaTieneDistrito(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudiZonaTieneDistrito(String usuario, Date fechaCambio, Integer fkcodigoZonaOld, Integer fkcodigoDistritoOld, Date versionOld, Integer fkcodigoZonaNew, Integer fkcodigoDistritoNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.fkcodigoZonaOld = fkcodigoZonaOld;
       this.fkcodigoDistritoOld = fkcodigoDistritoOld;
       this.versionOld = versionOld;
       this.fkcodigoZonaNew = fkcodigoZonaNew;
       this.fkcodigoDistritoNew = fkcodigoDistritoNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiZonaTieneDistrito() {
        return this.codigoAudiZonaTieneDistrito;
    }
    
    public void setCodigoAudiZonaTieneDistrito(Integer codigoAudiZonaTieneDistrito) {
        this.codigoAudiZonaTieneDistrito = codigoAudiZonaTieneDistrito;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public Integer getFkcodigoZonaOld() {
        return this.fkcodigoZonaOld;
    }
    
    public void setFkcodigoZonaOld(Integer fkcodigoZonaOld) {
        this.fkcodigoZonaOld = fkcodigoZonaOld;
    }
    public Integer getFkcodigoDistritoOld() {
        return this.fkcodigoDistritoOld;
    }
    
    public void setFkcodigoDistritoOld(Integer fkcodigoDistritoOld) {
        this.fkcodigoDistritoOld = fkcodigoDistritoOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public Integer getFkcodigoZonaNew() {
        return this.fkcodigoZonaNew;
    }
    
    public void setFkcodigoZonaNew(Integer fkcodigoZonaNew) {
        this.fkcodigoZonaNew = fkcodigoZonaNew;
    }
    public Integer getFkcodigoDistritoNew() {
        return this.fkcodigoDistritoNew;
    }
    
    public void setFkcodigoDistritoNew(Integer fkcodigoDistritoNew) {
        this.fkcodigoDistritoNew = fkcodigoDistritoNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


