package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaProducto generated by hbm2java
 */
public class AuditoriaProducto  implements java.io.Serializable {


     private Integer codigoAuditoriaProducto;
     private String usuario;
     private Date fechaCambio;
     private String nombreProductoOld;
     private Date ingresoAlmacenProductoOld;
     private Date salidaAlmacenProductoOld;
     private String stockProductoOld;
     private String preparacionProductoOld;
     private byte[] fotoProductoOld;
     private String coloresProductoOld;
     private String qrProductoOld;
     private Float pvvProductoOld;
     private Float pvfProductoOld;
     private Integer fkcodigoLineaOld;
     private Integer fkcodigoTipoProductoOld;
     private Integer fkcodigoEstadoProductoOld;
     private Date versionOld;
     private String nombreProductoNew;
     private Date ingresoAlmacenProductoNew;
     private Date salidaAlmacenProductoNew;
     private String stockProductoNew;
     private String preparacionProductoNew;
     private byte[] fotoProductoNew;
     private String coloresProductoNew;
     private String qrProductoNew;
     private Float pvvProductoNew;
     private Float pvfProductoNew;
     private Integer fkcodigoLineaNew;
     private Integer fkcodigoTipoProductoNew;
     private Integer fkcodigoEstadoProductoNew;
     private Date versionNew;

    public AuditoriaProducto() {
    }

	
    public AuditoriaProducto(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaProducto(String usuario, Date fechaCambio, String nombreProductoOld, Date ingresoAlmacenProductoOld, Date salidaAlmacenProductoOld, String stockProductoOld, String preparacionProductoOld, byte[] fotoProductoOld, String coloresProductoOld, String qrProductoOld, Float pvvProductoOld, Float pvfProductoOld, Integer fkcodigoLineaOld, Integer fkcodigoTipoProductoOld, Integer fkcodigoEstadoProductoOld, Date versionOld, String nombreProductoNew, Date ingresoAlmacenProductoNew, Date salidaAlmacenProductoNew, String stockProductoNew, String preparacionProductoNew, byte[] fotoProductoNew, String coloresProductoNew, String qrProductoNew, Float pvvProductoNew, Float pvfProductoNew, Integer fkcodigoLineaNew, Integer fkcodigoTipoProductoNew, Integer fkcodigoEstadoProductoNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreProductoOld = nombreProductoOld;
       this.ingresoAlmacenProductoOld = ingresoAlmacenProductoOld;
       this.salidaAlmacenProductoOld = salidaAlmacenProductoOld;
       this.stockProductoOld = stockProductoOld;
       this.preparacionProductoOld = preparacionProductoOld;
       this.fotoProductoOld = fotoProductoOld;
       this.coloresProductoOld = coloresProductoOld;
       this.qrProductoOld = qrProductoOld;
       this.pvvProductoOld = pvvProductoOld;
       this.pvfProductoOld = pvfProductoOld;
       this.fkcodigoLineaOld = fkcodigoLineaOld;
       this.fkcodigoTipoProductoOld = fkcodigoTipoProductoOld;
       this.fkcodigoEstadoProductoOld = fkcodigoEstadoProductoOld;
       this.versionOld = versionOld;
       this.nombreProductoNew = nombreProductoNew;
       this.ingresoAlmacenProductoNew = ingresoAlmacenProductoNew;
       this.salidaAlmacenProductoNew = salidaAlmacenProductoNew;
       this.stockProductoNew = stockProductoNew;
       this.preparacionProductoNew = preparacionProductoNew;
       this.fotoProductoNew = fotoProductoNew;
       this.coloresProductoNew = coloresProductoNew;
       this.qrProductoNew = qrProductoNew;
       this.pvvProductoNew = pvvProductoNew;
       this.pvfProductoNew = pvfProductoNew;
       this.fkcodigoLineaNew = fkcodigoLineaNew;
       this.fkcodigoTipoProductoNew = fkcodigoTipoProductoNew;
       this.fkcodigoEstadoProductoNew = fkcodigoEstadoProductoNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAuditoriaProducto() {
        return this.codigoAuditoriaProducto;
    }
    
    public void setCodigoAuditoriaProducto(Integer codigoAuditoriaProducto) {
        this.codigoAuditoriaProducto = codigoAuditoriaProducto;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreProductoOld() {
        return this.nombreProductoOld;
    }
    
    public void setNombreProductoOld(String nombreProductoOld) {
        this.nombreProductoOld = nombreProductoOld;
    }
    public Date getIngresoAlmacenProductoOld() {
        return this.ingresoAlmacenProductoOld;
    }
    
    public void setIngresoAlmacenProductoOld(Date ingresoAlmacenProductoOld) {
        this.ingresoAlmacenProductoOld = ingresoAlmacenProductoOld;
    }
    public Date getSalidaAlmacenProductoOld() {
        return this.salidaAlmacenProductoOld;
    }
    
    public void setSalidaAlmacenProductoOld(Date salidaAlmacenProductoOld) {
        this.salidaAlmacenProductoOld = salidaAlmacenProductoOld;
    }
    public String getStockProductoOld() {
        return this.stockProductoOld;
    }
    
    public void setStockProductoOld(String stockProductoOld) {
        this.stockProductoOld = stockProductoOld;
    }
    public String getPreparacionProductoOld() {
        return this.preparacionProductoOld;
    }
    
    public void setPreparacionProductoOld(String preparacionProductoOld) {
        this.preparacionProductoOld = preparacionProductoOld;
    }
    public byte[] getFotoProductoOld() {
        return this.fotoProductoOld;
    }
    
    public void setFotoProductoOld(byte[] fotoProductoOld) {
        this.fotoProductoOld = fotoProductoOld;
    }
    public String getColoresProductoOld() {
        return this.coloresProductoOld;
    }
    
    public void setColoresProductoOld(String coloresProductoOld) {
        this.coloresProductoOld = coloresProductoOld;
    }
    public String getQrProductoOld() {
        return this.qrProductoOld;
    }
    
    public void setQrProductoOld(String qrProductoOld) {
        this.qrProductoOld = qrProductoOld;
    }
    public Float getPvvProductoOld() {
        return this.pvvProductoOld;
    }
    
    public void setPvvProductoOld(Float pvvProductoOld) {
        this.pvvProductoOld = pvvProductoOld;
    }
    public Float getPvfProductoOld() {
        return this.pvfProductoOld;
    }
    
    public void setPvfProductoOld(Float pvfProductoOld) {
        this.pvfProductoOld = pvfProductoOld;
    }
    public Integer getFkcodigoLineaOld() {
        return this.fkcodigoLineaOld;
    }
    
    public void setFkcodigoLineaOld(Integer fkcodigoLineaOld) {
        this.fkcodigoLineaOld = fkcodigoLineaOld;
    }
    public Integer getFkcodigoTipoProductoOld() {
        return this.fkcodigoTipoProductoOld;
    }
    
    public void setFkcodigoTipoProductoOld(Integer fkcodigoTipoProductoOld) {
        this.fkcodigoTipoProductoOld = fkcodigoTipoProductoOld;
    }
    public Integer getFkcodigoEstadoProductoOld() {
        return this.fkcodigoEstadoProductoOld;
    }
    
    public void setFkcodigoEstadoProductoOld(Integer fkcodigoEstadoProductoOld) {
        this.fkcodigoEstadoProductoOld = fkcodigoEstadoProductoOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreProductoNew() {
        return this.nombreProductoNew;
    }
    
    public void setNombreProductoNew(String nombreProductoNew) {
        this.nombreProductoNew = nombreProductoNew;
    }
    public Date getIngresoAlmacenProductoNew() {
        return this.ingresoAlmacenProductoNew;
    }
    
    public void setIngresoAlmacenProductoNew(Date ingresoAlmacenProductoNew) {
        this.ingresoAlmacenProductoNew = ingresoAlmacenProductoNew;
    }
    public Date getSalidaAlmacenProductoNew() {
        return this.salidaAlmacenProductoNew;
    }
    
    public void setSalidaAlmacenProductoNew(Date salidaAlmacenProductoNew) {
        this.salidaAlmacenProductoNew = salidaAlmacenProductoNew;
    }
    public String getStockProductoNew() {
        return this.stockProductoNew;
    }
    
    public void setStockProductoNew(String stockProductoNew) {
        this.stockProductoNew = stockProductoNew;
    }
    public String getPreparacionProductoNew() {
        return this.preparacionProductoNew;
    }
    
    public void setPreparacionProductoNew(String preparacionProductoNew) {
        this.preparacionProductoNew = preparacionProductoNew;
    }
    public byte[] getFotoProductoNew() {
        return this.fotoProductoNew;
    }
    
    public void setFotoProductoNew(byte[] fotoProductoNew) {
        this.fotoProductoNew = fotoProductoNew;
    }
    public String getColoresProductoNew() {
        return this.coloresProductoNew;
    }
    
    public void setColoresProductoNew(String coloresProductoNew) {
        this.coloresProductoNew = coloresProductoNew;
    }
    public String getQrProductoNew() {
        return this.qrProductoNew;
    }
    
    public void setQrProductoNew(String qrProductoNew) {
        this.qrProductoNew = qrProductoNew;
    }
    public Float getPvvProductoNew() {
        return this.pvvProductoNew;
    }
    
    public void setPvvProductoNew(Float pvvProductoNew) {
        this.pvvProductoNew = pvvProductoNew;
    }
    public Float getPvfProductoNew() {
        return this.pvfProductoNew;
    }
    
    public void setPvfProductoNew(Float pvfProductoNew) {
        this.pvfProductoNew = pvfProductoNew;
    }
    public Integer getFkcodigoLineaNew() {
        return this.fkcodigoLineaNew;
    }
    
    public void setFkcodigoLineaNew(Integer fkcodigoLineaNew) {
        this.fkcodigoLineaNew = fkcodigoLineaNew;
    }
    public Integer getFkcodigoTipoProductoNew() {
        return this.fkcodigoTipoProductoNew;
    }
    
    public void setFkcodigoTipoProductoNew(Integer fkcodigoTipoProductoNew) {
        this.fkcodigoTipoProductoNew = fkcodigoTipoProductoNew;
    }
    public Integer getFkcodigoEstadoProductoNew() {
        return this.fkcodigoEstadoProductoNew;
    }
    
    public void setFkcodigoEstadoProductoNew(Integer fkcodigoEstadoProductoNew) {
        this.fkcodigoEstadoProductoNew = fkcodigoEstadoProductoNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


