package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudiCuotaPorLinea generated by hbm2java
 */
public class AudiCuotaPorLinea  implements java.io.Serializable {


     private Integer codigoAudiCuotaPorLinea;
     private String usuario;
     private Date fechaCambio;
     private Integer fkcodigoMesOld;
     private Integer fkcodigoLineaOld;
     private Float cuotaAsignadaOld;
     private Float cuotaRealizadaOld;
     private Integer fkcodigoMesNew;
     private Integer fkcodigoLineaNew;
     private Float cuotaAsignadaNew;
     private Float cuotaRealizadaNew;

    public AudiCuotaPorLinea() {
    }

	
    public AudiCuotaPorLinea(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudiCuotaPorLinea(String usuario, Date fechaCambio, Integer fkcodigoMesOld, Integer fkcodigoLineaOld, Float cuotaAsignadaOld, Float cuotaRealizadaOld, Integer fkcodigoMesNew, Integer fkcodigoLineaNew, Float cuotaAsignadaNew, Float cuotaRealizadaNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.fkcodigoMesOld = fkcodigoMesOld;
       this.fkcodigoLineaOld = fkcodigoLineaOld;
       this.cuotaAsignadaOld = cuotaAsignadaOld;
       this.cuotaRealizadaOld = cuotaRealizadaOld;
       this.fkcodigoMesNew = fkcodigoMesNew;
       this.fkcodigoLineaNew = fkcodigoLineaNew;
       this.cuotaAsignadaNew = cuotaAsignadaNew;
       this.cuotaRealizadaNew = cuotaRealizadaNew;
    }
   
    public Integer getCodigoAudiCuotaPorLinea() {
        return this.codigoAudiCuotaPorLinea;
    }
    
    public void setCodigoAudiCuotaPorLinea(Integer codigoAudiCuotaPorLinea) {
        this.codigoAudiCuotaPorLinea = codigoAudiCuotaPorLinea;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public Integer getFkcodigoMesOld() {
        return this.fkcodigoMesOld;
    }
    
    public void setFkcodigoMesOld(Integer fkcodigoMesOld) {
        this.fkcodigoMesOld = fkcodigoMesOld;
    }
    public Integer getFkcodigoLineaOld() {
        return this.fkcodigoLineaOld;
    }
    
    public void setFkcodigoLineaOld(Integer fkcodigoLineaOld) {
        this.fkcodigoLineaOld = fkcodigoLineaOld;
    }
    public Float getCuotaAsignadaOld() {
        return this.cuotaAsignadaOld;
    }
    
    public void setCuotaAsignadaOld(Float cuotaAsignadaOld) {
        this.cuotaAsignadaOld = cuotaAsignadaOld;
    }
    public Float getCuotaRealizadaOld() {
        return this.cuotaRealizadaOld;
    }
    
    public void setCuotaRealizadaOld(Float cuotaRealizadaOld) {
        this.cuotaRealizadaOld = cuotaRealizadaOld;
    }
    public Integer getFkcodigoMesNew() {
        return this.fkcodigoMesNew;
    }
    
    public void setFkcodigoMesNew(Integer fkcodigoMesNew) {
        this.fkcodigoMesNew = fkcodigoMesNew;
    }
    public Integer getFkcodigoLineaNew() {
        return this.fkcodigoLineaNew;
    }
    
    public void setFkcodigoLineaNew(Integer fkcodigoLineaNew) {
        this.fkcodigoLineaNew = fkcodigoLineaNew;
    }
    public Float getCuotaAsignadaNew() {
        return this.cuotaAsignadaNew;
    }
    
    public void setCuotaAsignadaNew(Float cuotaAsignadaNew) {
        this.cuotaAsignadaNew = cuotaAsignadaNew;
    }
    public Float getCuotaRealizadaNew() {
        return this.cuotaRealizadaNew;
    }
    
    public void setCuotaRealizadaNew(Float cuotaRealizadaNew) {
        this.cuotaRealizadaNew = cuotaRealizadaNew;
    }




}


