package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaTipoUsuario generated by hbm2java
 */
public class AuditoriaTipoUsuario  implements java.io.Serializable {


     private Integer codigoAudiTipoUsuario;
     private String usuario;
     private Date fechaCambio;
     private String nombreTipoUsuarioOld;
     private Date versionOld;
     private String nombreTipoUsuarioNew;
     private Date versionNew;

    public AuditoriaTipoUsuario() {
    }

	
    public AuditoriaTipoUsuario(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaTipoUsuario(String usuario, Date fechaCambio, String nombreTipoUsuarioOld, Date versionOld, String nombreTipoUsuarioNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreTipoUsuarioOld = nombreTipoUsuarioOld;
       this.versionOld = versionOld;
       this.nombreTipoUsuarioNew = nombreTipoUsuarioNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiTipoUsuario() {
        return this.codigoAudiTipoUsuario;
    }
    
    public void setCodigoAudiTipoUsuario(Integer codigoAudiTipoUsuario) {
        this.codigoAudiTipoUsuario = codigoAudiTipoUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreTipoUsuarioOld() {
        return this.nombreTipoUsuarioOld;
    }
    
    public void setNombreTipoUsuarioOld(String nombreTipoUsuarioOld) {
        this.nombreTipoUsuarioOld = nombreTipoUsuarioOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreTipoUsuarioNew() {
        return this.nombreTipoUsuarioNew;
    }
    
    public void setNombreTipoUsuarioNew(String nombreTipoUsuarioNew) {
        this.nombreTipoUsuarioNew = nombreTipoUsuarioNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


