package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaEstadoInsumo generated by hbm2java
 */
public class AuditoriaEstadoInsumo  implements java.io.Serializable {


     private Integer codigoAudiEstadoInsumo;
     private String usuario;
     private Date fechaCambio;
     private String nombreEstadoInsumoOld;
     private Date versionOld;
     private String nombreEstadoInsumoNew;
     private Date versionNew;

    public AuditoriaEstadoInsumo() {
    }

	
    public AuditoriaEstadoInsumo(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaEstadoInsumo(String usuario, Date fechaCambio, String nombreEstadoInsumoOld, Date versionOld, String nombreEstadoInsumoNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreEstadoInsumoOld = nombreEstadoInsumoOld;
       this.versionOld = versionOld;
       this.nombreEstadoInsumoNew = nombreEstadoInsumoNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiEstadoInsumo() {
        return this.codigoAudiEstadoInsumo;
    }
    
    public void setCodigoAudiEstadoInsumo(Integer codigoAudiEstadoInsumo) {
        this.codigoAudiEstadoInsumo = codigoAudiEstadoInsumo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreEstadoInsumoOld() {
        return this.nombreEstadoInsumoOld;
    }
    
    public void setNombreEstadoInsumoOld(String nombreEstadoInsumoOld) {
        this.nombreEstadoInsumoOld = nombreEstadoInsumoOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreEstadoInsumoNew() {
        return this.nombreEstadoInsumoNew;
    }
    
    public void setNombreEstadoInsumoNew(String nombreEstadoInsumoNew) {
        this.nombreEstadoInsumoNew = nombreEstadoInsumoNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


