package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaTipoProducto generated by hbm2java
 */
public class AuditoriaTipoProducto  implements java.io.Serializable {


     private Integer codigoAudiTipoProducto;
     private String usuario;
     private Date fechaCambio;
     private String nombreTipoProductoOld;
     private Float tiempoenhornoTipoProductoOld;
     private Float temperaturaenhornoTipoProductoOld;
     private byte[] fotoTipoProductoOld;
     private String nombreTipoProductoNew;
     private Float tiempoenhornoTipoProductoNew;
     private Float temperaturaenhornoTipoProductoNew;
     private byte[] fotoTipoProductoNew;

    public AuditoriaTipoProducto() {
    }

	
    public AuditoriaTipoProducto(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaTipoProducto(String usuario, Date fechaCambio, String nombreTipoProductoOld, Float tiempoenhornoTipoProductoOld, Float temperaturaenhornoTipoProductoOld, byte[] fotoTipoProductoOld, String nombreTipoProductoNew, Float tiempoenhornoTipoProductoNew, Float temperaturaenhornoTipoProductoNew, byte[] fotoTipoProductoNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreTipoProductoOld = nombreTipoProductoOld;
       this.tiempoenhornoTipoProductoOld = tiempoenhornoTipoProductoOld;
       this.temperaturaenhornoTipoProductoOld = temperaturaenhornoTipoProductoOld;
       this.fotoTipoProductoOld = fotoTipoProductoOld;
       this.nombreTipoProductoNew = nombreTipoProductoNew;
       this.tiempoenhornoTipoProductoNew = tiempoenhornoTipoProductoNew;
       this.temperaturaenhornoTipoProductoNew = temperaturaenhornoTipoProductoNew;
       this.fotoTipoProductoNew = fotoTipoProductoNew;
    }
   
    public Integer getCodigoAudiTipoProducto() {
        return this.codigoAudiTipoProducto;
    }
    
    public void setCodigoAudiTipoProducto(Integer codigoAudiTipoProducto) {
        this.codigoAudiTipoProducto = codigoAudiTipoProducto;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreTipoProductoOld() {
        return this.nombreTipoProductoOld;
    }
    
    public void setNombreTipoProductoOld(String nombreTipoProductoOld) {
        this.nombreTipoProductoOld = nombreTipoProductoOld;
    }
    public Float getTiempoenhornoTipoProductoOld() {
        return this.tiempoenhornoTipoProductoOld;
    }
    
    public void setTiempoenhornoTipoProductoOld(Float tiempoenhornoTipoProductoOld) {
        this.tiempoenhornoTipoProductoOld = tiempoenhornoTipoProductoOld;
    }
    public Float getTemperaturaenhornoTipoProductoOld() {
        return this.temperaturaenhornoTipoProductoOld;
    }
    
    public void setTemperaturaenhornoTipoProductoOld(Float temperaturaenhornoTipoProductoOld) {
        this.temperaturaenhornoTipoProductoOld = temperaturaenhornoTipoProductoOld;
    }
    public byte[] getFotoTipoProductoOld() {
        return this.fotoTipoProductoOld;
    }
    
    public void setFotoTipoProductoOld(byte[] fotoTipoProductoOld) {
        this.fotoTipoProductoOld = fotoTipoProductoOld;
    }
    public String getNombreTipoProductoNew() {
        return this.nombreTipoProductoNew;
    }
    
    public void setNombreTipoProductoNew(String nombreTipoProductoNew) {
        this.nombreTipoProductoNew = nombreTipoProductoNew;
    }
    public Float getTiempoenhornoTipoProductoNew() {
        return this.tiempoenhornoTipoProductoNew;
    }
    
    public void setTiempoenhornoTipoProductoNew(Float tiempoenhornoTipoProductoNew) {
        this.tiempoenhornoTipoProductoNew = tiempoenhornoTipoProductoNew;
    }
    public Float getTemperaturaenhornoTipoProductoNew() {
        return this.temperaturaenhornoTipoProductoNew;
    }
    
    public void setTemperaturaenhornoTipoProductoNew(Float temperaturaenhornoTipoProductoNew) {
        this.temperaturaenhornoTipoProductoNew = temperaturaenhornoTipoProductoNew;
    }
    public byte[] getFotoTipoProductoNew() {
        return this.fotoTipoProductoNew;
    }
    
    public void setFotoTipoProductoNew(byte[] fotoTipoProductoNew) {
        this.fotoTipoProductoNew = fotoTipoProductoNew;
    }




}


