package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaTipoImpuesto generated by hbm2java
 */
public class AuditoriaTipoImpuesto  implements java.io.Serializable {


     private Integer codigoAudiTipoImpuesto;
     private String usuario;
     private Date fechaCambio;
     private String nombreTipoImpuestoOld;
     private Float porcentajeTipoImpuestoOld;
     private String nombreTipoImpuestoNew;
     private Float porcentajeTipoImpuestoNew;

    public AuditoriaTipoImpuesto() {
    }

	
    public AuditoriaTipoImpuesto(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaTipoImpuesto(String usuario, Date fechaCambio, String nombreTipoImpuestoOld, Float porcentajeTipoImpuestoOld, String nombreTipoImpuestoNew, Float porcentajeTipoImpuestoNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreTipoImpuestoOld = nombreTipoImpuestoOld;
       this.porcentajeTipoImpuestoOld = porcentajeTipoImpuestoOld;
       this.nombreTipoImpuestoNew = nombreTipoImpuestoNew;
       this.porcentajeTipoImpuestoNew = porcentajeTipoImpuestoNew;
    }
   
    public Integer getCodigoAudiTipoImpuesto() {
        return this.codigoAudiTipoImpuesto;
    }
    
    public void setCodigoAudiTipoImpuesto(Integer codigoAudiTipoImpuesto) {
        this.codigoAudiTipoImpuesto = codigoAudiTipoImpuesto;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreTipoImpuestoOld() {
        return this.nombreTipoImpuestoOld;
    }
    
    public void setNombreTipoImpuestoOld(String nombreTipoImpuestoOld) {
        this.nombreTipoImpuestoOld = nombreTipoImpuestoOld;
    }
    public Float getPorcentajeTipoImpuestoOld() {
        return this.porcentajeTipoImpuestoOld;
    }
    
    public void setPorcentajeTipoImpuestoOld(Float porcentajeTipoImpuestoOld) {
        this.porcentajeTipoImpuestoOld = porcentajeTipoImpuestoOld;
    }
    public String getNombreTipoImpuestoNew() {
        return this.nombreTipoImpuestoNew;
    }
    
    public void setNombreTipoImpuestoNew(String nombreTipoImpuestoNew) {
        this.nombreTipoImpuestoNew = nombreTipoImpuestoNew;
    }
    public Float getPorcentajeTipoImpuestoNew() {
        return this.porcentajeTipoImpuestoNew;
    }
    
    public void setPorcentajeTipoImpuestoNew(Float porcentajeTipoImpuestoNew) {
        this.porcentajeTipoImpuestoNew = porcentajeTipoImpuestoNew;
    }




}


