package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudiCatalogo generated by hbm2java
 */
public class AudiCatalogo  implements java.io.Serializable {


     private Integer codigoAudiCatalogo;
     private String usuario;
     private Date fechaCambio;
     private Integer catCodigoProductoOld;
     private String catNombreProductoOld;
     private String catNombreTipoProductoOld;
     private Float catTiempoenhornoTipoProductoOld;
     private Float catTemperaturaenhornoTipoProductoOld;
     private Float catValorNetoOld;
     private Float catValorConIgvOld;
     private byte[] catFotoProductoOld;
     private String catPreparacionProductoOld;
     private String catColoresProductoOld;
     private String catNombreInsumoOld;
     private String catModeloRecetaProductoOld;
     private Integer cantidadMasPedidoOld;
     private Float promedioTotalProdOld;
     private Integer fkcodigoEstadoCatalogoOld;
     private Date versionOld;
     private Integer catCodigoProductoNew;
     private String catNombreProductoNew;
     private String catNombreTipoProductoNew;
     private Float catTiempoenhornoTipoProductoNew;
     private Float catTemperaturaenhornoTipoProductoNew;
     private Float catValorNetoNew;
     private Float catValorConIgvNew;
     private byte[] catFotoProductoNew;
     private String catPreparacionProductoNew;
     private String catColoresProductoNew;
     private String catNombreInsumoNew;
     private String catModeloRecetaProductoNew;
     private Integer cantidadMasPedidoNew;
     private Float promedioTotalProdNew;
     private Integer fkcodigoEstadoCatalogoNew;
     private Date versionNew;

    public AudiCatalogo() {
    }

	
    public AudiCatalogo(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudiCatalogo(String usuario, Date fechaCambio, Integer catCodigoProductoOld, String catNombreProductoOld, String catNombreTipoProductoOld, Float catTiempoenhornoTipoProductoOld, Float catTemperaturaenhornoTipoProductoOld, Float catValorNetoOld, Float catValorConIgvOld, byte[] catFotoProductoOld, String catPreparacionProductoOld, String catColoresProductoOld, String catNombreInsumoOld, String catModeloRecetaProductoOld, Integer cantidadMasPedidoOld, Float promedioTotalProdOld, Integer fkcodigoEstadoCatalogoOld, Date versionOld, Integer catCodigoProductoNew, String catNombreProductoNew, String catNombreTipoProductoNew, Float catTiempoenhornoTipoProductoNew, Float catTemperaturaenhornoTipoProductoNew, Float catValorNetoNew, Float catValorConIgvNew, byte[] catFotoProductoNew, String catPreparacionProductoNew, String catColoresProductoNew, String catNombreInsumoNew, String catModeloRecetaProductoNew, Integer cantidadMasPedidoNew, Float promedioTotalProdNew, Integer fkcodigoEstadoCatalogoNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.catCodigoProductoOld = catCodigoProductoOld;
       this.catNombreProductoOld = catNombreProductoOld;
       this.catNombreTipoProductoOld = catNombreTipoProductoOld;
       this.catTiempoenhornoTipoProductoOld = catTiempoenhornoTipoProductoOld;
       this.catTemperaturaenhornoTipoProductoOld = catTemperaturaenhornoTipoProductoOld;
       this.catValorNetoOld = catValorNetoOld;
       this.catValorConIgvOld = catValorConIgvOld;
       this.catFotoProductoOld = catFotoProductoOld;
       this.catPreparacionProductoOld = catPreparacionProductoOld;
       this.catColoresProductoOld = catColoresProductoOld;
       this.catNombreInsumoOld = catNombreInsumoOld;
       this.catModeloRecetaProductoOld = catModeloRecetaProductoOld;
       this.cantidadMasPedidoOld = cantidadMasPedidoOld;
       this.promedioTotalProdOld = promedioTotalProdOld;
       this.fkcodigoEstadoCatalogoOld = fkcodigoEstadoCatalogoOld;
       this.versionOld = versionOld;
       this.catCodigoProductoNew = catCodigoProductoNew;
       this.catNombreProductoNew = catNombreProductoNew;
       this.catNombreTipoProductoNew = catNombreTipoProductoNew;
       this.catTiempoenhornoTipoProductoNew = catTiempoenhornoTipoProductoNew;
       this.catTemperaturaenhornoTipoProductoNew = catTemperaturaenhornoTipoProductoNew;
       this.catValorNetoNew = catValorNetoNew;
       this.catValorConIgvNew = catValorConIgvNew;
       this.catFotoProductoNew = catFotoProductoNew;
       this.catPreparacionProductoNew = catPreparacionProductoNew;
       this.catColoresProductoNew = catColoresProductoNew;
       this.catNombreInsumoNew = catNombreInsumoNew;
       this.catModeloRecetaProductoNew = catModeloRecetaProductoNew;
       this.cantidadMasPedidoNew = cantidadMasPedidoNew;
       this.promedioTotalProdNew = promedioTotalProdNew;
       this.fkcodigoEstadoCatalogoNew = fkcodigoEstadoCatalogoNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiCatalogo() {
        return this.codigoAudiCatalogo;
    }
    
    public void setCodigoAudiCatalogo(Integer codigoAudiCatalogo) {
        this.codigoAudiCatalogo = codigoAudiCatalogo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public Integer getCatCodigoProductoOld() {
        return this.catCodigoProductoOld;
    }
    
    public void setCatCodigoProductoOld(Integer catCodigoProductoOld) {
        this.catCodigoProductoOld = catCodigoProductoOld;
    }
    public String getCatNombreProductoOld() {
        return this.catNombreProductoOld;
    }
    
    public void setCatNombreProductoOld(String catNombreProductoOld) {
        this.catNombreProductoOld = catNombreProductoOld;
    }
    public String getCatNombreTipoProductoOld() {
        return this.catNombreTipoProductoOld;
    }
    
    public void setCatNombreTipoProductoOld(String catNombreTipoProductoOld) {
        this.catNombreTipoProductoOld = catNombreTipoProductoOld;
    }
    public Float getCatTiempoenhornoTipoProductoOld() {
        return this.catTiempoenhornoTipoProductoOld;
    }
    
    public void setCatTiempoenhornoTipoProductoOld(Float catTiempoenhornoTipoProductoOld) {
        this.catTiempoenhornoTipoProductoOld = catTiempoenhornoTipoProductoOld;
    }
    public Float getCatTemperaturaenhornoTipoProductoOld() {
        return this.catTemperaturaenhornoTipoProductoOld;
    }
    
    public void setCatTemperaturaenhornoTipoProductoOld(Float catTemperaturaenhornoTipoProductoOld) {
        this.catTemperaturaenhornoTipoProductoOld = catTemperaturaenhornoTipoProductoOld;
    }
    public Float getCatValorNetoOld() {
        return this.catValorNetoOld;
    }
    
    public void setCatValorNetoOld(Float catValorNetoOld) {
        this.catValorNetoOld = catValorNetoOld;
    }
    public Float getCatValorConIgvOld() {
        return this.catValorConIgvOld;
    }
    
    public void setCatValorConIgvOld(Float catValorConIgvOld) {
        this.catValorConIgvOld = catValorConIgvOld;
    }
    public byte[] getCatFotoProductoOld() {
        return this.catFotoProductoOld;
    }
    
    public void setCatFotoProductoOld(byte[] catFotoProductoOld) {
        this.catFotoProductoOld = catFotoProductoOld;
    }
    public String getCatPreparacionProductoOld() {
        return this.catPreparacionProductoOld;
    }
    
    public void setCatPreparacionProductoOld(String catPreparacionProductoOld) {
        this.catPreparacionProductoOld = catPreparacionProductoOld;
    }
    public String getCatColoresProductoOld() {
        return this.catColoresProductoOld;
    }
    
    public void setCatColoresProductoOld(String catColoresProductoOld) {
        this.catColoresProductoOld = catColoresProductoOld;
    }
    public String getCatNombreInsumoOld() {
        return this.catNombreInsumoOld;
    }
    
    public void setCatNombreInsumoOld(String catNombreInsumoOld) {
        this.catNombreInsumoOld = catNombreInsumoOld;
    }
    public String getCatModeloRecetaProductoOld() {
        return this.catModeloRecetaProductoOld;
    }
    
    public void setCatModeloRecetaProductoOld(String catModeloRecetaProductoOld) {
        this.catModeloRecetaProductoOld = catModeloRecetaProductoOld;
    }
    public Integer getCantidadMasPedidoOld() {
        return this.cantidadMasPedidoOld;
    }
    
    public void setCantidadMasPedidoOld(Integer cantidadMasPedidoOld) {
        this.cantidadMasPedidoOld = cantidadMasPedidoOld;
    }
    public Float getPromedioTotalProdOld() {
        return this.promedioTotalProdOld;
    }
    
    public void setPromedioTotalProdOld(Float promedioTotalProdOld) {
        this.promedioTotalProdOld = promedioTotalProdOld;
    }
    public Integer getFkcodigoEstadoCatalogoOld() {
        return this.fkcodigoEstadoCatalogoOld;
    }
    
    public void setFkcodigoEstadoCatalogoOld(Integer fkcodigoEstadoCatalogoOld) {
        this.fkcodigoEstadoCatalogoOld = fkcodigoEstadoCatalogoOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public Integer getCatCodigoProductoNew() {
        return this.catCodigoProductoNew;
    }
    
    public void setCatCodigoProductoNew(Integer catCodigoProductoNew) {
        this.catCodigoProductoNew = catCodigoProductoNew;
    }
    public String getCatNombreProductoNew() {
        return this.catNombreProductoNew;
    }
    
    public void setCatNombreProductoNew(String catNombreProductoNew) {
        this.catNombreProductoNew = catNombreProductoNew;
    }
    public String getCatNombreTipoProductoNew() {
        return this.catNombreTipoProductoNew;
    }
    
    public void setCatNombreTipoProductoNew(String catNombreTipoProductoNew) {
        this.catNombreTipoProductoNew = catNombreTipoProductoNew;
    }
    public Float getCatTiempoenhornoTipoProductoNew() {
        return this.catTiempoenhornoTipoProductoNew;
    }
    
    public void setCatTiempoenhornoTipoProductoNew(Float catTiempoenhornoTipoProductoNew) {
        this.catTiempoenhornoTipoProductoNew = catTiempoenhornoTipoProductoNew;
    }
    public Float getCatTemperaturaenhornoTipoProductoNew() {
        return this.catTemperaturaenhornoTipoProductoNew;
    }
    
    public void setCatTemperaturaenhornoTipoProductoNew(Float catTemperaturaenhornoTipoProductoNew) {
        this.catTemperaturaenhornoTipoProductoNew = catTemperaturaenhornoTipoProductoNew;
    }
    public Float getCatValorNetoNew() {
        return this.catValorNetoNew;
    }
    
    public void setCatValorNetoNew(Float catValorNetoNew) {
        this.catValorNetoNew = catValorNetoNew;
    }
    public Float getCatValorConIgvNew() {
        return this.catValorConIgvNew;
    }
    
    public void setCatValorConIgvNew(Float catValorConIgvNew) {
        this.catValorConIgvNew = catValorConIgvNew;
    }
    public byte[] getCatFotoProductoNew() {
        return this.catFotoProductoNew;
    }
    
    public void setCatFotoProductoNew(byte[] catFotoProductoNew) {
        this.catFotoProductoNew = catFotoProductoNew;
    }
    public String getCatPreparacionProductoNew() {
        return this.catPreparacionProductoNew;
    }
    
    public void setCatPreparacionProductoNew(String catPreparacionProductoNew) {
        this.catPreparacionProductoNew = catPreparacionProductoNew;
    }
    public String getCatColoresProductoNew() {
        return this.catColoresProductoNew;
    }
    
    public void setCatColoresProductoNew(String catColoresProductoNew) {
        this.catColoresProductoNew = catColoresProductoNew;
    }
    public String getCatNombreInsumoNew() {
        return this.catNombreInsumoNew;
    }
    
    public void setCatNombreInsumoNew(String catNombreInsumoNew) {
        this.catNombreInsumoNew = catNombreInsumoNew;
    }
    public String getCatModeloRecetaProductoNew() {
        return this.catModeloRecetaProductoNew;
    }
    
    public void setCatModeloRecetaProductoNew(String catModeloRecetaProductoNew) {
        this.catModeloRecetaProductoNew = catModeloRecetaProductoNew;
    }
    public Integer getCantidadMasPedidoNew() {
        return this.cantidadMasPedidoNew;
    }
    
    public void setCantidadMasPedidoNew(Integer cantidadMasPedidoNew) {
        this.cantidadMasPedidoNew = cantidadMasPedidoNew;
    }
    public Float getPromedioTotalProdNew() {
        return this.promedioTotalProdNew;
    }
    
    public void setPromedioTotalProdNew(Float promedioTotalProdNew) {
        this.promedioTotalProdNew = promedioTotalProdNew;
    }
    public Integer getFkcodigoEstadoCatalogoNew() {
        return this.fkcodigoEstadoCatalogoNew;
    }
    
    public void setFkcodigoEstadoCatalogoNew(Integer fkcodigoEstadoCatalogoNew) {
        this.fkcodigoEstadoCatalogoNew = fkcodigoEstadoCatalogoNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


