package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaCuota generated by hbm2java
 */
public class AuditoriaCuota  implements java.io.Serializable {


     private Integer codigoAuditoriaCuota;
     private String usuario;
     private Date fechaCambio;
     private Float montoCuoataOld;
     private Integer fkcodigoMesOld;
     private Integer fkcodigoProductoOld;
     private Float montoCuoataNew;
     private Integer fkcodigoMesNew;
     private Integer fkcodigoProductoNew;

    public AuditoriaCuota() {
    }

	
    public AuditoriaCuota(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaCuota(String usuario, Date fechaCambio, Float montoCuoataOld, Integer fkcodigoMesOld, Integer fkcodigoProductoOld, Float montoCuoataNew, Integer fkcodigoMesNew, Integer fkcodigoProductoNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.montoCuoataOld = montoCuoataOld;
       this.fkcodigoMesOld = fkcodigoMesOld;
       this.fkcodigoProductoOld = fkcodigoProductoOld;
       this.montoCuoataNew = montoCuoataNew;
       this.fkcodigoMesNew = fkcodigoMesNew;
       this.fkcodigoProductoNew = fkcodigoProductoNew;
    }
   
    public Integer getCodigoAuditoriaCuota() {
        return this.codigoAuditoriaCuota;
    }
    
    public void setCodigoAuditoriaCuota(Integer codigoAuditoriaCuota) {
        this.codigoAuditoriaCuota = codigoAuditoriaCuota;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public Float getMontoCuoataOld() {
        return this.montoCuoataOld;
    }
    
    public void setMontoCuoataOld(Float montoCuoataOld) {
        this.montoCuoataOld = montoCuoataOld;
    }
    public Integer getFkcodigoMesOld() {
        return this.fkcodigoMesOld;
    }
    
    public void setFkcodigoMesOld(Integer fkcodigoMesOld) {
        this.fkcodigoMesOld = fkcodigoMesOld;
    }
    public Integer getFkcodigoProductoOld() {
        return this.fkcodigoProductoOld;
    }
    
    public void setFkcodigoProductoOld(Integer fkcodigoProductoOld) {
        this.fkcodigoProductoOld = fkcodigoProductoOld;
    }
    public Float getMontoCuoataNew() {
        return this.montoCuoataNew;
    }
    
    public void setMontoCuoataNew(Float montoCuoataNew) {
        this.montoCuoataNew = montoCuoataNew;
    }
    public Integer getFkcodigoMesNew() {
        return this.fkcodigoMesNew;
    }
    
    public void setFkcodigoMesNew(Integer fkcodigoMesNew) {
        this.fkcodigoMesNew = fkcodigoMesNew;
    }
    public Integer getFkcodigoProductoNew() {
        return this.fkcodigoProductoNew;
    }
    
    public void setFkcodigoProductoNew(Integer fkcodigoProductoNew) {
        this.fkcodigoProductoNew = fkcodigoProductoNew;
    }




}


