package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaProvincia generated by hbm2java
 */
public class AuditoriaProvincia  implements java.io.Serializable {


     private Integer codigoAudiProvincia;
     private String usuario;
     private Date fechaCambio;
     private Integer fkcodigoPaisOld;
     private String nombreProvinciaOld;
     private Date versionOld;
     private String fkcodigoPaisNew;
     private String nombreProvinciaNew;
     private Date versionNew;

    public AuditoriaProvincia() {
    }

	
    public AuditoriaProvincia(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaProvincia(String usuario, Date fechaCambio, Integer fkcodigoPaisOld, String nombreProvinciaOld, Date versionOld, String fkcodigoPaisNew, String nombreProvinciaNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.fkcodigoPaisOld = fkcodigoPaisOld;
       this.nombreProvinciaOld = nombreProvinciaOld;
       this.versionOld = versionOld;
       this.fkcodigoPaisNew = fkcodigoPaisNew;
       this.nombreProvinciaNew = nombreProvinciaNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiProvincia() {
        return this.codigoAudiProvincia;
    }
    
    public void setCodigoAudiProvincia(Integer codigoAudiProvincia) {
        this.codigoAudiProvincia = codigoAudiProvincia;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public Integer getFkcodigoPaisOld() {
        return this.fkcodigoPaisOld;
    }
    
    public void setFkcodigoPaisOld(Integer fkcodigoPaisOld) {
        this.fkcodigoPaisOld = fkcodigoPaisOld;
    }
    public String getNombreProvinciaOld() {
        return this.nombreProvinciaOld;
    }
    
    public void setNombreProvinciaOld(String nombreProvinciaOld) {
        this.nombreProvinciaOld = nombreProvinciaOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getFkcodigoPaisNew() {
        return this.fkcodigoPaisNew;
    }
    
    public void setFkcodigoPaisNew(String fkcodigoPaisNew) {
        this.fkcodigoPaisNew = fkcodigoPaisNew;
    }
    public String getNombreProvinciaNew() {
        return this.nombreProvinciaNew;
    }
    
    public void setNombreProvinciaNew(String nombreProvinciaNew) {
        this.nombreProvinciaNew = nombreProvinciaNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


