package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaCliente generated by hbm2java
 */
public class AuditoriaCliente  implements java.io.Serializable {


     private Integer codigoAudiCliente;
     private String usuario;
     private Date fechaCambio;
     private String razonsocialClienteOld;
     private Integer fkcodigoUsuarioOld;
     private Integer fkcodigoRegimenClienteOld;
     private Integer fkcodigoEstadoClienteOld;
     private Float latitudClienteOld;
     private Float longitudClienteOld;
     private String typeClienteOld;
     private byte[] fotoUbicacionClienteOld;
     private String rucClienteOld;
     private String dniClienteOld;
     private Date fechaEmpadronamientoClienteOld;
     private Date versionOld;
     private String razonsocialClienteNew;
     private Integer fkcodigoUsuarioNew;
     private Integer fkcodigoRegimenClienteNew;
     private Integer fkcodigoEstadoClienteNew;
     private Float latitudClienteNew;
     private Float longitudClienteNew;
     private String typeClienteNew;
     private byte[] fotoUbicacionClienteNew;
     private String rucClienteNew;
     private String dniClienteNew;
     private Date fechaEmpadronamientoClienteNew;
     private Date versionNew;

    public AuditoriaCliente() {
    }

	
    public AuditoriaCliente(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaCliente(String usuario, Date fechaCambio, String razonsocialClienteOld, Integer fkcodigoUsuarioOld, Integer fkcodigoRegimenClienteOld, Integer fkcodigoEstadoClienteOld, Float latitudClienteOld, Float longitudClienteOld, String typeClienteOld, byte[] fotoUbicacionClienteOld, String rucClienteOld, String dniClienteOld, Date fechaEmpadronamientoClienteOld, Date versionOld, String razonsocialClienteNew, Integer fkcodigoUsuarioNew, Integer fkcodigoRegimenClienteNew, Integer fkcodigoEstadoClienteNew, Float latitudClienteNew, Float longitudClienteNew, String typeClienteNew, byte[] fotoUbicacionClienteNew, String rucClienteNew, String dniClienteNew, Date fechaEmpadronamientoClienteNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.razonsocialClienteOld = razonsocialClienteOld;
       this.fkcodigoUsuarioOld = fkcodigoUsuarioOld;
       this.fkcodigoRegimenClienteOld = fkcodigoRegimenClienteOld;
       this.fkcodigoEstadoClienteOld = fkcodigoEstadoClienteOld;
       this.latitudClienteOld = latitudClienteOld;
       this.longitudClienteOld = longitudClienteOld;
       this.typeClienteOld = typeClienteOld;
       this.fotoUbicacionClienteOld = fotoUbicacionClienteOld;
       this.rucClienteOld = rucClienteOld;
       this.dniClienteOld = dniClienteOld;
       this.fechaEmpadronamientoClienteOld = fechaEmpadronamientoClienteOld;
       this.versionOld = versionOld;
       this.razonsocialClienteNew = razonsocialClienteNew;
       this.fkcodigoUsuarioNew = fkcodigoUsuarioNew;
       this.fkcodigoRegimenClienteNew = fkcodigoRegimenClienteNew;
       this.fkcodigoEstadoClienteNew = fkcodigoEstadoClienteNew;
       this.latitudClienteNew = latitudClienteNew;
       this.longitudClienteNew = longitudClienteNew;
       this.typeClienteNew = typeClienteNew;
       this.fotoUbicacionClienteNew = fotoUbicacionClienteNew;
       this.rucClienteNew = rucClienteNew;
       this.dniClienteNew = dniClienteNew;
       this.fechaEmpadronamientoClienteNew = fechaEmpadronamientoClienteNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiCliente() {
        return this.codigoAudiCliente;
    }
    
    public void setCodigoAudiCliente(Integer codigoAudiCliente) {
        this.codigoAudiCliente = codigoAudiCliente;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getRazonsocialClienteOld() {
        return this.razonsocialClienteOld;
    }
    
    public void setRazonsocialClienteOld(String razonsocialClienteOld) {
        this.razonsocialClienteOld = razonsocialClienteOld;
    }
    public Integer getFkcodigoUsuarioOld() {
        return this.fkcodigoUsuarioOld;
    }
    
    public void setFkcodigoUsuarioOld(Integer fkcodigoUsuarioOld) {
        this.fkcodigoUsuarioOld = fkcodigoUsuarioOld;
    }
    public Integer getFkcodigoRegimenClienteOld() {
        return this.fkcodigoRegimenClienteOld;
    }
    
    public void setFkcodigoRegimenClienteOld(Integer fkcodigoRegimenClienteOld) {
        this.fkcodigoRegimenClienteOld = fkcodigoRegimenClienteOld;
    }
    public Integer getFkcodigoEstadoClienteOld() {
        return this.fkcodigoEstadoClienteOld;
    }
    
    public void setFkcodigoEstadoClienteOld(Integer fkcodigoEstadoClienteOld) {
        this.fkcodigoEstadoClienteOld = fkcodigoEstadoClienteOld;
    }
    public Float getLatitudClienteOld() {
        return this.latitudClienteOld;
    }
    
    public void setLatitudClienteOld(Float latitudClienteOld) {
        this.latitudClienteOld = latitudClienteOld;
    }
    public Float getLongitudClienteOld() {
        return this.longitudClienteOld;
    }
    
    public void setLongitudClienteOld(Float longitudClienteOld) {
        this.longitudClienteOld = longitudClienteOld;
    }
    public String getTypeClienteOld() {
        return this.typeClienteOld;
    }
    
    public void setTypeClienteOld(String typeClienteOld) {
        this.typeClienteOld = typeClienteOld;
    }
    public byte[] getFotoUbicacionClienteOld() {
        return this.fotoUbicacionClienteOld;
    }
    
    public void setFotoUbicacionClienteOld(byte[] fotoUbicacionClienteOld) {
        this.fotoUbicacionClienteOld = fotoUbicacionClienteOld;
    }
    public String getRucClienteOld() {
        return this.rucClienteOld;
    }
    
    public void setRucClienteOld(String rucClienteOld) {
        this.rucClienteOld = rucClienteOld;
    }
    public String getDniClienteOld() {
        return this.dniClienteOld;
    }
    
    public void setDniClienteOld(String dniClienteOld) {
        this.dniClienteOld = dniClienteOld;
    }
    public Date getFechaEmpadronamientoClienteOld() {
        return this.fechaEmpadronamientoClienteOld;
    }
    
    public void setFechaEmpadronamientoClienteOld(Date fechaEmpadronamientoClienteOld) {
        this.fechaEmpadronamientoClienteOld = fechaEmpadronamientoClienteOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getRazonsocialClienteNew() {
        return this.razonsocialClienteNew;
    }
    
    public void setRazonsocialClienteNew(String razonsocialClienteNew) {
        this.razonsocialClienteNew = razonsocialClienteNew;
    }
    public Integer getFkcodigoUsuarioNew() {
        return this.fkcodigoUsuarioNew;
    }
    
    public void setFkcodigoUsuarioNew(Integer fkcodigoUsuarioNew) {
        this.fkcodigoUsuarioNew = fkcodigoUsuarioNew;
    }
    public Integer getFkcodigoRegimenClienteNew() {
        return this.fkcodigoRegimenClienteNew;
    }
    
    public void setFkcodigoRegimenClienteNew(Integer fkcodigoRegimenClienteNew) {
        this.fkcodigoRegimenClienteNew = fkcodigoRegimenClienteNew;
    }
    public Integer getFkcodigoEstadoClienteNew() {
        return this.fkcodigoEstadoClienteNew;
    }
    
    public void setFkcodigoEstadoClienteNew(Integer fkcodigoEstadoClienteNew) {
        this.fkcodigoEstadoClienteNew = fkcodigoEstadoClienteNew;
    }
    public Float getLatitudClienteNew() {
        return this.latitudClienteNew;
    }
    
    public void setLatitudClienteNew(Float latitudClienteNew) {
        this.latitudClienteNew = latitudClienteNew;
    }
    public Float getLongitudClienteNew() {
        return this.longitudClienteNew;
    }
    
    public void setLongitudClienteNew(Float longitudClienteNew) {
        this.longitudClienteNew = longitudClienteNew;
    }
    public String getTypeClienteNew() {
        return this.typeClienteNew;
    }
    
    public void setTypeClienteNew(String typeClienteNew) {
        this.typeClienteNew = typeClienteNew;
    }
    public byte[] getFotoUbicacionClienteNew() {
        return this.fotoUbicacionClienteNew;
    }
    
    public void setFotoUbicacionClienteNew(byte[] fotoUbicacionClienteNew) {
        this.fotoUbicacionClienteNew = fotoUbicacionClienteNew;
    }
    public String getRucClienteNew() {
        return this.rucClienteNew;
    }
    
    public void setRucClienteNew(String rucClienteNew) {
        this.rucClienteNew = rucClienteNew;
    }
    public String getDniClienteNew() {
        return this.dniClienteNew;
    }
    
    public void setDniClienteNew(String dniClienteNew) {
        this.dniClienteNew = dniClienteNew;
    }
    public Date getFechaEmpadronamientoClienteNew() {
        return this.fechaEmpadronamientoClienteNew;
    }
    
    public void setFechaEmpadronamientoClienteNew(Date fechaEmpadronamientoClienteNew) {
        this.fechaEmpadronamientoClienteNew = fechaEmpadronamientoClienteNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


