package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaMes generated by hbm2java
 */
public class AuditoriaMes  implements java.io.Serializable {


     private Integer codigoAuditoriaMes;
     private String usuario;
     private Date fechaCambio;
     private String nombreMesOld;
     private Integer fkCodigoYearOld;
     private Date versionOld;
     private String nombreMesNew;
     private Integer fkCodigoYearNew;
     private Date versionNew;

    public AuditoriaMes() {
    }

	
    public AuditoriaMes(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaMes(String usuario, Date fechaCambio, String nombreMesOld, Integer fkCodigoYearOld, Date versionOld, String nombreMesNew, Integer fkCodigoYearNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreMesOld = nombreMesOld;
       this.fkCodigoYearOld = fkCodigoYearOld;
       this.versionOld = versionOld;
       this.nombreMesNew = nombreMesNew;
       this.fkCodigoYearNew = fkCodigoYearNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAuditoriaMes() {
        return this.codigoAuditoriaMes;
    }
    
    public void setCodigoAuditoriaMes(Integer codigoAuditoriaMes) {
        this.codigoAuditoriaMes = codigoAuditoriaMes;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreMesOld() {
        return this.nombreMesOld;
    }
    
    public void setNombreMesOld(String nombreMesOld) {
        this.nombreMesOld = nombreMesOld;
    }
    public Integer getFkCodigoYearOld() {
        return this.fkCodigoYearOld;
    }
    
    public void setFkCodigoYearOld(Integer fkCodigoYearOld) {
        this.fkCodigoYearOld = fkCodigoYearOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreMesNew() {
        return this.nombreMesNew;
    }
    
    public void setNombreMesNew(String nombreMesNew) {
        this.nombreMesNew = nombreMesNew;
    }
    public Integer getFkCodigoYearNew() {
        return this.fkCodigoYearNew;
    }
    
    public void setFkCodigoYearNew(Integer fkCodigoYearNew) {
        this.fkCodigoYearNew = fkCodigoYearNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


