package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudiEClienteTienePedido generated by hbm2java
 */
public class AudiEClienteTienePedido  implements java.io.Serializable {


     private Integer codigoAudiEstadoClienteTienePedido;
     private String usuario;
     private Date fechaCambio;
     private String nombreEstadoClienteTienePedidoOld;
     private byte[] fotoEstadoClienteTienePedidoOld;
     private String nombreEstadoClienteTienePedidoNew;
     private byte[] fotoEstadoClienteTienePedidoNew;

    public AudiEClienteTienePedido() {
    }

	
    public AudiEClienteTienePedido(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudiEClienteTienePedido(String usuario, Date fechaCambio, String nombreEstadoClienteTienePedidoOld, byte[] fotoEstadoClienteTienePedidoOld, String nombreEstadoClienteTienePedidoNew, byte[] fotoEstadoClienteTienePedidoNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreEstadoClienteTienePedidoOld = nombreEstadoClienteTienePedidoOld;
       this.fotoEstadoClienteTienePedidoOld = fotoEstadoClienteTienePedidoOld;
       this.nombreEstadoClienteTienePedidoNew = nombreEstadoClienteTienePedidoNew;
       this.fotoEstadoClienteTienePedidoNew = fotoEstadoClienteTienePedidoNew;
    }
   
    public Integer getCodigoAudiEstadoClienteTienePedido() {
        return this.codigoAudiEstadoClienteTienePedido;
    }
    
    public void setCodigoAudiEstadoClienteTienePedido(Integer codigoAudiEstadoClienteTienePedido) {
        this.codigoAudiEstadoClienteTienePedido = codigoAudiEstadoClienteTienePedido;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreEstadoClienteTienePedidoOld() {
        return this.nombreEstadoClienteTienePedidoOld;
    }
    
    public void setNombreEstadoClienteTienePedidoOld(String nombreEstadoClienteTienePedidoOld) {
        this.nombreEstadoClienteTienePedidoOld = nombreEstadoClienteTienePedidoOld;
    }
    public byte[] getFotoEstadoClienteTienePedidoOld() {
        return this.fotoEstadoClienteTienePedidoOld;
    }
    
    public void setFotoEstadoClienteTienePedidoOld(byte[] fotoEstadoClienteTienePedidoOld) {
        this.fotoEstadoClienteTienePedidoOld = fotoEstadoClienteTienePedidoOld;
    }
    public String getNombreEstadoClienteTienePedidoNew() {
        return this.nombreEstadoClienteTienePedidoNew;
    }
    
    public void setNombreEstadoClienteTienePedidoNew(String nombreEstadoClienteTienePedidoNew) {
        this.nombreEstadoClienteTienePedidoNew = nombreEstadoClienteTienePedidoNew;
    }
    public byte[] getFotoEstadoClienteTienePedidoNew() {
        return this.fotoEstadoClienteTienePedidoNew;
    }
    
    public void setFotoEstadoClienteTienePedidoNew(byte[] fotoEstadoClienteTienePedidoNew) {
        this.fotoEstadoClienteTienePedidoNew = fotoEstadoClienteTienePedidoNew;
    }




}


