package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaTipoUsuario generated by hbm2java
 */
public class AuditoriaTipoUsuario  implements java.io.Serializable {


     private Integer codigoAudiTipoUsuario;
     private String usuario;
     private Date fechaCambio;
     private String nombreTipoUsuarioOld;
     private String nombreTipoUsuarioNew;

    public AuditoriaTipoUsuario() {
    }

	
    public AuditoriaTipoUsuario(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaTipoUsuario(String usuario, Date fechaCambio, String nombreTipoUsuarioOld, String nombreTipoUsuarioNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreTipoUsuarioOld = nombreTipoUsuarioOld;
       this.nombreTipoUsuarioNew = nombreTipoUsuarioNew;
    }
   
    public Integer getCodigoAudiTipoUsuario() {
        return this.codigoAudiTipoUsuario;
    }
    
    public void setCodigoAudiTipoUsuario(Integer codigoAudiTipoUsuario) {
        this.codigoAudiTipoUsuario = codigoAudiTipoUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreTipoUsuarioOld() {
        return this.nombreTipoUsuarioOld;
    }
    
    public void setNombreTipoUsuarioOld(String nombreTipoUsuarioOld) {
        this.nombreTipoUsuarioOld = nombreTipoUsuarioOld;
    }
    public String getNombreTipoUsuarioNew() {
        return this.nombreTipoUsuarioNew;
    }
    
    public void setNombreTipoUsuarioNew(String nombreTipoUsuarioNew) {
        this.nombreTipoUsuarioNew = nombreTipoUsuarioNew;
    }




}


