package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaZona generated by hbm2java
 */
public class AuditoriaZona  implements java.io.Serializable {


     private Integer codigoAudiZona;
     private String usuario;
     private Date fechaCambio;
     private String nombreZonaOld;
     private Date versionOld;
     private String nombreZonaNew;
     private Date versionNew;

    public AuditoriaZona() {
    }

	
    public AuditoriaZona(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaZona(String usuario, Date fechaCambio, String nombreZonaOld, Date versionOld, String nombreZonaNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreZonaOld = nombreZonaOld;
       this.versionOld = versionOld;
       this.nombreZonaNew = nombreZonaNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiZona() {
        return this.codigoAudiZona;
    }
    
    public void setCodigoAudiZona(Integer codigoAudiZona) {
        this.codigoAudiZona = codigoAudiZona;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreZonaOld() {
        return this.nombreZonaOld;
    }
    
    public void setNombreZonaOld(String nombreZonaOld) {
        this.nombreZonaOld = nombreZonaOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreZonaNew() {
        return this.nombreZonaNew;
    }
    
    public void setNombreZonaNew(String nombreZonaNew) {
        this.nombreZonaNew = nombreZonaNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


