package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaPais generated by hbm2java
 */
public class AuditoriaPais  implements java.io.Serializable {


     private Integer codigoAudiPais;
     private String usuario;
     private Date fechaCambio;
     private String nombrePaisOld;
     private String nombrePaisNew;

    public AuditoriaPais() {
    }

	
    public AuditoriaPais(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaPais(String usuario, Date fechaCambio, String nombrePaisOld, String nombrePaisNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombrePaisOld = nombrePaisOld;
       this.nombrePaisNew = nombrePaisNew;
    }
   
    public Integer getCodigoAudiPais() {
        return this.codigoAudiPais;
    }
    
    public void setCodigoAudiPais(Integer codigoAudiPais) {
        this.codigoAudiPais = codigoAudiPais;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombrePaisOld() {
        return this.nombrePaisOld;
    }
    
    public void setNombrePaisOld(String nombrePaisOld) {
        this.nombrePaisOld = nombrePaisOld;
    }
    public String getNombrePaisNew() {
        return this.nombrePaisNew;
    }
    
    public void setNombrePaisNew(String nombrePaisNew) {
        this.nombrePaisNew = nombrePaisNew;
    }




}


