package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudiPromocionVenta generated by hbm2java
 */
public class AudiPromocionVenta  implements java.io.Serializable {


     private Integer codigoAudiPromocionVenta;
     private String usuario;
     private Date fechaCambio;
     private Integer cantidadSkuPedidoOld;
     private Float descuentoSkuPedidoOld;
     private Date fechaInicioPromocionOld;
     private Date fechaExpiracionPromocionOld;
     private String descripcionPromocionOld;
     private Integer cantidadSkuPedidoNew;
     private Float descuentoSkuPedidoNew;
     private Date fechaInicioPromocionNew;
     private Date fechaExpiracionPromocionNew;
     private String descripcionPromocionNew;

    public AudiPromocionVenta() {
    }

	
    public AudiPromocionVenta(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudiPromocionVenta(String usuario, Date fechaCambio, Integer cantidadSkuPedidoOld, Float descuentoSkuPedidoOld, Date fechaInicioPromocionOld, Date fechaExpiracionPromocionOld, String descripcionPromocionOld, Integer cantidadSkuPedidoNew, Float descuentoSkuPedidoNew, Date fechaInicioPromocionNew, Date fechaExpiracionPromocionNew, String descripcionPromocionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.cantidadSkuPedidoOld = cantidadSkuPedidoOld;
       this.descuentoSkuPedidoOld = descuentoSkuPedidoOld;
       this.fechaInicioPromocionOld = fechaInicioPromocionOld;
       this.fechaExpiracionPromocionOld = fechaExpiracionPromocionOld;
       this.descripcionPromocionOld = descripcionPromocionOld;
       this.cantidadSkuPedidoNew = cantidadSkuPedidoNew;
       this.descuentoSkuPedidoNew = descuentoSkuPedidoNew;
       this.fechaInicioPromocionNew = fechaInicioPromocionNew;
       this.fechaExpiracionPromocionNew = fechaExpiracionPromocionNew;
       this.descripcionPromocionNew = descripcionPromocionNew;
    }
   
    public Integer getCodigoAudiPromocionVenta() {
        return this.codigoAudiPromocionVenta;
    }
    
    public void setCodigoAudiPromocionVenta(Integer codigoAudiPromocionVenta) {
        this.codigoAudiPromocionVenta = codigoAudiPromocionVenta;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public Integer getCantidadSkuPedidoOld() {
        return this.cantidadSkuPedidoOld;
    }
    
    public void setCantidadSkuPedidoOld(Integer cantidadSkuPedidoOld) {
        this.cantidadSkuPedidoOld = cantidadSkuPedidoOld;
    }
    public Float getDescuentoSkuPedidoOld() {
        return this.descuentoSkuPedidoOld;
    }
    
    public void setDescuentoSkuPedidoOld(Float descuentoSkuPedidoOld) {
        this.descuentoSkuPedidoOld = descuentoSkuPedidoOld;
    }
    public Date getFechaInicioPromocionOld() {
        return this.fechaInicioPromocionOld;
    }
    
    public void setFechaInicioPromocionOld(Date fechaInicioPromocionOld) {
        this.fechaInicioPromocionOld = fechaInicioPromocionOld;
    }
    public Date getFechaExpiracionPromocionOld() {
        return this.fechaExpiracionPromocionOld;
    }
    
    public void setFechaExpiracionPromocionOld(Date fechaExpiracionPromocionOld) {
        this.fechaExpiracionPromocionOld = fechaExpiracionPromocionOld;
    }
    public String getDescripcionPromocionOld() {
        return this.descripcionPromocionOld;
    }
    
    public void setDescripcionPromocionOld(String descripcionPromocionOld) {
        this.descripcionPromocionOld = descripcionPromocionOld;
    }
    public Integer getCantidadSkuPedidoNew() {
        return this.cantidadSkuPedidoNew;
    }
    
    public void setCantidadSkuPedidoNew(Integer cantidadSkuPedidoNew) {
        this.cantidadSkuPedidoNew = cantidadSkuPedidoNew;
    }
    public Float getDescuentoSkuPedidoNew() {
        return this.descuentoSkuPedidoNew;
    }
    
    public void setDescuentoSkuPedidoNew(Float descuentoSkuPedidoNew) {
        this.descuentoSkuPedidoNew = descuentoSkuPedidoNew;
    }
    public Date getFechaInicioPromocionNew() {
        return this.fechaInicioPromocionNew;
    }
    
    public void setFechaInicioPromocionNew(Date fechaInicioPromocionNew) {
        this.fechaInicioPromocionNew = fechaInicioPromocionNew;
    }
    public Date getFechaExpiracionPromocionNew() {
        return this.fechaExpiracionPromocionNew;
    }
    
    public void setFechaExpiracionPromocionNew(Date fechaExpiracionPromocionNew) {
        this.fechaExpiracionPromocionNew = fechaExpiracionPromocionNew;
    }
    public String getDescripcionPromocionNew() {
        return this.descripcionPromocionNew;
    }
    
    public void setDescripcionPromocionNew(String descripcionPromocionNew) {
        this.descripcionPromocionNew = descripcionPromocionNew;
    }




}


