package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaTipoInsumo generated by hbm2java
 */
public class AuditoriaTipoInsumo  implements java.io.Serializable {


     private Integer codigoAudiTipoInsumo;
     private String usuario;
     private Date fechaCambio;
     private String nombreTipoInsumoOld;
     private Date versionOld;
     private String nombreTipoInsumoNew;
     private Date versionNew;

    public AuditoriaTipoInsumo() {
    }

	
    public AuditoriaTipoInsumo(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaTipoInsumo(String usuario, Date fechaCambio, String nombreTipoInsumoOld, Date versionOld, String nombreTipoInsumoNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreTipoInsumoOld = nombreTipoInsumoOld;
       this.versionOld = versionOld;
       this.nombreTipoInsumoNew = nombreTipoInsumoNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiTipoInsumo() {
        return this.codigoAudiTipoInsumo;
    }
    
    public void setCodigoAudiTipoInsumo(Integer codigoAudiTipoInsumo) {
        this.codigoAudiTipoInsumo = codigoAudiTipoInsumo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreTipoInsumoOld() {
        return this.nombreTipoInsumoOld;
    }
    
    public void setNombreTipoInsumoOld(String nombreTipoInsumoOld) {
        this.nombreTipoInsumoOld = nombreTipoInsumoOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreTipoInsumoNew() {
        return this.nombreTipoInsumoNew;
    }
    
    public void setNombreTipoInsumoNew(String nombreTipoInsumoNew) {
        this.nombreTipoInsumoNew = nombreTipoInsumoNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


