package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaEstadoProducto generated by hbm2java
 */
public class AuditoriaEstadoProducto  implements java.io.Serializable {


     private Integer codigoAudiEstadoProducto;
     private String usuario;
     private Date fechaCambio;
     private String nombreEstadoProductoOld;
     private Date versionOld;
     private String nombreEstadoProductoNew;
     private Date versionNew;

    public AuditoriaEstadoProducto() {
    }

	
    public AuditoriaEstadoProducto(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaEstadoProducto(String usuario, Date fechaCambio, String nombreEstadoProductoOld, Date versionOld, String nombreEstadoProductoNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreEstadoProductoOld = nombreEstadoProductoOld;
       this.versionOld = versionOld;
       this.nombreEstadoProductoNew = nombreEstadoProductoNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiEstadoProducto() {
        return this.codigoAudiEstadoProducto;
    }
    
    public void setCodigoAudiEstadoProducto(Integer codigoAudiEstadoProducto) {
        this.codigoAudiEstadoProducto = codigoAudiEstadoProducto;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreEstadoProductoOld() {
        return this.nombreEstadoProductoOld;
    }
    
    public void setNombreEstadoProductoOld(String nombreEstadoProductoOld) {
        this.nombreEstadoProductoOld = nombreEstadoProductoOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreEstadoProductoNew() {
        return this.nombreEstadoProductoNew;
    }
    
    public void setNombreEstadoProductoNew(String nombreEstadoProductoNew) {
        this.nombreEstadoProductoNew = nombreEstadoProductoNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


