package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaInsumo generated by hbm2java
 */
public class AuditoriaInsumo  implements java.io.Serializable {


     private Integer codigoAudiInsumo;
     private String usuario;
     private Date fechaCambio;
     private String nombreInsumoOld;
     private String marcaInsumoOld;
     private Date fechaIngresoInsumoOld;
     private Float pesoInsumoOld;
     private String presentacionInsumoOld;
     private Float precioUnitarioInsumoOld;
     private String nombreInsumoNew;
     private String marcaInsumoNew;
     private Date fechaIngresoInsumoNew;
     private Float pesoInsumoNew;
     private String presentacionInsumoNew;
     private Float precioUnitarioInsumoNew;

    public AuditoriaInsumo() {
    }

	
    public AuditoriaInsumo(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaInsumo(String usuario, Date fechaCambio, String nombreInsumoOld, String marcaInsumoOld, Date fechaIngresoInsumoOld, Float pesoInsumoOld, String presentacionInsumoOld, Float precioUnitarioInsumoOld, String nombreInsumoNew, String marcaInsumoNew, Date fechaIngresoInsumoNew, Float pesoInsumoNew, String presentacionInsumoNew, Float precioUnitarioInsumoNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreInsumoOld = nombreInsumoOld;
       this.marcaInsumoOld = marcaInsumoOld;
       this.fechaIngresoInsumoOld = fechaIngresoInsumoOld;
       this.pesoInsumoOld = pesoInsumoOld;
       this.presentacionInsumoOld = presentacionInsumoOld;
       this.precioUnitarioInsumoOld = precioUnitarioInsumoOld;
       this.nombreInsumoNew = nombreInsumoNew;
       this.marcaInsumoNew = marcaInsumoNew;
       this.fechaIngresoInsumoNew = fechaIngresoInsumoNew;
       this.pesoInsumoNew = pesoInsumoNew;
       this.presentacionInsumoNew = presentacionInsumoNew;
       this.precioUnitarioInsumoNew = precioUnitarioInsumoNew;
    }
   
    public Integer getCodigoAudiInsumo() {
        return this.codigoAudiInsumo;
    }
    
    public void setCodigoAudiInsumo(Integer codigoAudiInsumo) {
        this.codigoAudiInsumo = codigoAudiInsumo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreInsumoOld() {
        return this.nombreInsumoOld;
    }
    
    public void setNombreInsumoOld(String nombreInsumoOld) {
        this.nombreInsumoOld = nombreInsumoOld;
    }
    public String getMarcaInsumoOld() {
        return this.marcaInsumoOld;
    }
    
    public void setMarcaInsumoOld(String marcaInsumoOld) {
        this.marcaInsumoOld = marcaInsumoOld;
    }
    public Date getFechaIngresoInsumoOld() {
        return this.fechaIngresoInsumoOld;
    }
    
    public void setFechaIngresoInsumoOld(Date fechaIngresoInsumoOld) {
        this.fechaIngresoInsumoOld = fechaIngresoInsumoOld;
    }
    public Float getPesoInsumoOld() {
        return this.pesoInsumoOld;
    }
    
    public void setPesoInsumoOld(Float pesoInsumoOld) {
        this.pesoInsumoOld = pesoInsumoOld;
    }
    public String getPresentacionInsumoOld() {
        return this.presentacionInsumoOld;
    }
    
    public void setPresentacionInsumoOld(String presentacionInsumoOld) {
        this.presentacionInsumoOld = presentacionInsumoOld;
    }
    public Float getPrecioUnitarioInsumoOld() {
        return this.precioUnitarioInsumoOld;
    }
    
    public void setPrecioUnitarioInsumoOld(Float precioUnitarioInsumoOld) {
        this.precioUnitarioInsumoOld = precioUnitarioInsumoOld;
    }
    public String getNombreInsumoNew() {
        return this.nombreInsumoNew;
    }
    
    public void setNombreInsumoNew(String nombreInsumoNew) {
        this.nombreInsumoNew = nombreInsumoNew;
    }
    public String getMarcaInsumoNew() {
        return this.marcaInsumoNew;
    }
    
    public void setMarcaInsumoNew(String marcaInsumoNew) {
        this.marcaInsumoNew = marcaInsumoNew;
    }
    public Date getFechaIngresoInsumoNew() {
        return this.fechaIngresoInsumoNew;
    }
    
    public void setFechaIngresoInsumoNew(Date fechaIngresoInsumoNew) {
        this.fechaIngresoInsumoNew = fechaIngresoInsumoNew;
    }
    public Float getPesoInsumoNew() {
        return this.pesoInsumoNew;
    }
    
    public void setPesoInsumoNew(Float pesoInsumoNew) {
        this.pesoInsumoNew = pesoInsumoNew;
    }
    public String getPresentacionInsumoNew() {
        return this.presentacionInsumoNew;
    }
    
    public void setPresentacionInsumoNew(String presentacionInsumoNew) {
        this.presentacionInsumoNew = presentacionInsumoNew;
    }
    public Float getPrecioUnitarioInsumoNew() {
        return this.precioUnitarioInsumoNew;
    }
    
    public void setPrecioUnitarioInsumoNew(Float precioUnitarioInsumoNew) {
        this.precioUnitarioInsumoNew = precioUnitarioInsumoNew;
    }




}


