package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaRegimenCliente generated by hbm2java
 */
public class AuditoriaRegimenCliente  implements java.io.Serializable {


     private Integer codigoAudiRegimenCliente;
     private String usuario;
     private Date fechaCambio;
     private String nombreRegimenClienteOld;
     private Date versionOld;
     private String nombreRegimenClienteNew;
     private Date versionNew;

    public AuditoriaRegimenCliente() {
    }

	
    public AuditoriaRegimenCliente(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaRegimenCliente(String usuario, Date fechaCambio, String nombreRegimenClienteOld, Date versionOld, String nombreRegimenClienteNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreRegimenClienteOld = nombreRegimenClienteOld;
       this.versionOld = versionOld;
       this.nombreRegimenClienteNew = nombreRegimenClienteNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiRegimenCliente() {
        return this.codigoAudiRegimenCliente;
    }
    
    public void setCodigoAudiRegimenCliente(Integer codigoAudiRegimenCliente) {
        this.codigoAudiRegimenCliente = codigoAudiRegimenCliente;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreRegimenClienteOld() {
        return this.nombreRegimenClienteOld;
    }
    
    public void setNombreRegimenClienteOld(String nombreRegimenClienteOld) {
        this.nombreRegimenClienteOld = nombreRegimenClienteOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreRegimenClienteNew() {
        return this.nombreRegimenClienteNew;
    }
    
    public void setNombreRegimenClienteNew(String nombreRegimenClienteNew) {
        this.nombreRegimenClienteNew = nombreRegimenClienteNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


