package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudiRecetaPTieneInsumo generated by hbm2java
 */
public class AudiRecetaPTieneInsumo  implements java.io.Serializable {


     private Integer codigoAudiRecetaProductoTieneInsumo;
     private String usuario;
     private Date fechaCambio;
     private Integer fkcodigoProductoOld;
     private Integer fkcodigoInsumoOld;
     private Integer fkcodigoRecetaProductoOld;
     private Integer fkcodigoProductoNew;
     private Integer fkcodigoInsumoNew;
     private Integer fkcodigoRecetaProductoNew;

    public AudiRecetaPTieneInsumo() {
    }

	
    public AudiRecetaPTieneInsumo(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudiRecetaPTieneInsumo(String usuario, Date fechaCambio, Integer fkcodigoProductoOld, Integer fkcodigoInsumoOld, Integer fkcodigoRecetaProductoOld, Integer fkcodigoProductoNew, Integer fkcodigoInsumoNew, Integer fkcodigoRecetaProductoNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.fkcodigoProductoOld = fkcodigoProductoOld;
       this.fkcodigoInsumoOld = fkcodigoInsumoOld;
       this.fkcodigoRecetaProductoOld = fkcodigoRecetaProductoOld;
       this.fkcodigoProductoNew = fkcodigoProductoNew;
       this.fkcodigoInsumoNew = fkcodigoInsumoNew;
       this.fkcodigoRecetaProductoNew = fkcodigoRecetaProductoNew;
    }
   
    public Integer getCodigoAudiRecetaProductoTieneInsumo() {
        return this.codigoAudiRecetaProductoTieneInsumo;
    }
    
    public void setCodigoAudiRecetaProductoTieneInsumo(Integer codigoAudiRecetaProductoTieneInsumo) {
        this.codigoAudiRecetaProductoTieneInsumo = codigoAudiRecetaProductoTieneInsumo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public Integer getFkcodigoProductoOld() {
        return this.fkcodigoProductoOld;
    }
    
    public void setFkcodigoProductoOld(Integer fkcodigoProductoOld) {
        this.fkcodigoProductoOld = fkcodigoProductoOld;
    }
    public Integer getFkcodigoInsumoOld() {
        return this.fkcodigoInsumoOld;
    }
    
    public void setFkcodigoInsumoOld(Integer fkcodigoInsumoOld) {
        this.fkcodigoInsumoOld = fkcodigoInsumoOld;
    }
    public Integer getFkcodigoRecetaProductoOld() {
        return this.fkcodigoRecetaProductoOld;
    }
    
    public void setFkcodigoRecetaProductoOld(Integer fkcodigoRecetaProductoOld) {
        this.fkcodigoRecetaProductoOld = fkcodigoRecetaProductoOld;
    }
    public Integer getFkcodigoProductoNew() {
        return this.fkcodigoProductoNew;
    }
    
    public void setFkcodigoProductoNew(Integer fkcodigoProductoNew) {
        this.fkcodigoProductoNew = fkcodigoProductoNew;
    }
    public Integer getFkcodigoInsumoNew() {
        return this.fkcodigoInsumoNew;
    }
    
    public void setFkcodigoInsumoNew(Integer fkcodigoInsumoNew) {
        this.fkcodigoInsumoNew = fkcodigoInsumoNew;
    }
    public Integer getFkcodigoRecetaProductoNew() {
        return this.fkcodigoRecetaProductoNew;
    }
    
    public void setFkcodigoRecetaProductoNew(Integer fkcodigoRecetaProductoNew) {
        this.fkcodigoRecetaProductoNew = fkcodigoRecetaProductoNew;
    }




}


