package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaLinea generated by hbm2java
 */
public class AuditoriaLinea  implements java.io.Serializable {


     private Integer codigoAudiLinea;
     private String usuario;
     private Date fechaCambio;
     private String nombreLineaOld;
     private byte[] iconoLineaOld;
     private String nombreLineaNew;
     private byte[] iconoLineaNew;

    public AuditoriaLinea() {
    }

	
    public AuditoriaLinea(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaLinea(String usuario, Date fechaCambio, String nombreLineaOld, byte[] iconoLineaOld, String nombreLineaNew, byte[] iconoLineaNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreLineaOld = nombreLineaOld;
       this.iconoLineaOld = iconoLineaOld;
       this.nombreLineaNew = nombreLineaNew;
       this.iconoLineaNew = iconoLineaNew;
    }
   
    public Integer getCodigoAudiLinea() {
        return this.codigoAudiLinea;
    }
    
    public void setCodigoAudiLinea(Integer codigoAudiLinea) {
        this.codigoAudiLinea = codigoAudiLinea;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreLineaOld() {
        return this.nombreLineaOld;
    }
    
    public void setNombreLineaOld(String nombreLineaOld) {
        this.nombreLineaOld = nombreLineaOld;
    }
    public byte[] getIconoLineaOld() {
        return this.iconoLineaOld;
    }
    
    public void setIconoLineaOld(byte[] iconoLineaOld) {
        this.iconoLineaOld = iconoLineaOld;
    }
    public String getNombreLineaNew() {
        return this.nombreLineaNew;
    }
    
    public void setNombreLineaNew(String nombreLineaNew) {
        this.nombreLineaNew = nombreLineaNew;
    }
    public byte[] getIconoLineaNew() {
        return this.iconoLineaNew;
    }
    
    public void setIconoLineaNew(byte[] iconoLineaNew) {
        this.iconoLineaNew = iconoLineaNew;
    }




}


