package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudiEstadoCatalogo generated by hbm2java
 */
public class AudiEstadoCatalogo  implements java.io.Serializable {


     private Integer codigoAudiEstadoCatalogo;
     private String usuario;
     private Date fechaCambio;
     private String descripcionOld;
     private Date versionOld;
     private String descripcionNew;
     private Date versionNew;

    public AudiEstadoCatalogo() {
    }

	
    public AudiEstadoCatalogo(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudiEstadoCatalogo(String usuario, Date fechaCambio, String descripcionOld, Date versionOld, String descripcionNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.descripcionOld = descripcionOld;
       this.versionOld = versionOld;
       this.descripcionNew = descripcionNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiEstadoCatalogo() {
        return this.codigoAudiEstadoCatalogo;
    }
    
    public void setCodigoAudiEstadoCatalogo(Integer codigoAudiEstadoCatalogo) {
        this.codigoAudiEstadoCatalogo = codigoAudiEstadoCatalogo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getDescripcionOld() {
        return this.descripcionOld;
    }
    
    public void setDescripcionOld(String descripcionOld) {
        this.descripcionOld = descripcionOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getDescripcionNew() {
        return this.descripcionNew;
    }
    
    public void setDescripcionNew(String descripcionNew) {
        this.descripcionNew = descripcionNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


