package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaEstadoUsuario generated by hbm2java
 */
public class AuditoriaEstadoUsuario  implements java.io.Serializable {


     private Integer codigoAudiEstadoUsuario;
     private String usuario;
     private Date fechaCambio;
     private String nombreEstadoUsuarioOld;
     private String nombreEstadoUsuarioNew;

    public AuditoriaEstadoUsuario() {
    }

	
    public AuditoriaEstadoUsuario(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaEstadoUsuario(String usuario, Date fechaCambio, String nombreEstadoUsuarioOld, String nombreEstadoUsuarioNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreEstadoUsuarioOld = nombreEstadoUsuarioOld;
       this.nombreEstadoUsuarioNew = nombreEstadoUsuarioNew;
    }
   
    public Integer getCodigoAudiEstadoUsuario() {
        return this.codigoAudiEstadoUsuario;
    }
    
    public void setCodigoAudiEstadoUsuario(Integer codigoAudiEstadoUsuario) {
        this.codigoAudiEstadoUsuario = codigoAudiEstadoUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreEstadoUsuarioOld() {
        return this.nombreEstadoUsuarioOld;
    }
    
    public void setNombreEstadoUsuarioOld(String nombreEstadoUsuarioOld) {
        this.nombreEstadoUsuarioOld = nombreEstadoUsuarioOld;
    }
    public String getNombreEstadoUsuarioNew() {
        return this.nombreEstadoUsuarioNew;
    }
    
    public void setNombreEstadoUsuarioNew(String nombreEstadoUsuarioNew) {
        this.nombreEstadoUsuarioNew = nombreEstadoUsuarioNew;
    }




}


