package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaCiudad generated by hbm2java
 */
public class AuditoriaCiudad  implements java.io.Serializable {


     private Integer codigoAudiCiudad;
     private String usuario;
     private Date fechaCambio;
     private Integer fkcodigoProvinciaOld;
     private String nombreCiudadOld;
     private String fkcodigoProvinciaNew;
     private String nombreCiudadNew;

    public AuditoriaCiudad() {
    }

	
    public AuditoriaCiudad(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaCiudad(String usuario, Date fechaCambio, Integer fkcodigoProvinciaOld, String nombreCiudadOld, String fkcodigoProvinciaNew, String nombreCiudadNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.fkcodigoProvinciaOld = fkcodigoProvinciaOld;
       this.nombreCiudadOld = nombreCiudadOld;
       this.fkcodigoProvinciaNew = fkcodigoProvinciaNew;
       this.nombreCiudadNew = nombreCiudadNew;
    }
   
    public Integer getCodigoAudiCiudad() {
        return this.codigoAudiCiudad;
    }
    
    public void setCodigoAudiCiudad(Integer codigoAudiCiudad) {
        this.codigoAudiCiudad = codigoAudiCiudad;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public Integer getFkcodigoProvinciaOld() {
        return this.fkcodigoProvinciaOld;
    }
    
    public void setFkcodigoProvinciaOld(Integer fkcodigoProvinciaOld) {
        this.fkcodigoProvinciaOld = fkcodigoProvinciaOld;
    }
    public String getNombreCiudadOld() {
        return this.nombreCiudadOld;
    }
    
    public void setNombreCiudadOld(String nombreCiudadOld) {
        this.nombreCiudadOld = nombreCiudadOld;
    }
    public String getFkcodigoProvinciaNew() {
        return this.fkcodigoProvinciaNew;
    }
    
    public void setFkcodigoProvinciaNew(String fkcodigoProvinciaNew) {
        this.fkcodigoProvinciaNew = fkcodigoProvinciaNew;
    }
    public String getNombreCiudadNew() {
        return this.nombreCiudadNew;
    }
    
    public void setNombreCiudadNew(String nombreCiudadNew) {
        this.nombreCiudadNew = nombreCiudadNew;
    }




}


