package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaMes generated by hbm2java
 */
public class AuditoriaMes  implements java.io.Serializable {


     private Integer codigoAuditoriaMes;
     private String usuario;
     private Date fechaCambio;
     private String nombreMesOld;
     private Integer fkcodigoYearOld;
     private String nombreMesNew;
     private Integer fkcodigoYearNew;

    public AuditoriaMes() {
    }

	
    public AuditoriaMes(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaMes(String usuario, Date fechaCambio, String nombreMesOld, Integer fkcodigoYearOld, String nombreMesNew, Integer fkcodigoYearNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreMesOld = nombreMesOld;
       this.fkcodigoYearOld = fkcodigoYearOld;
       this.nombreMesNew = nombreMesNew;
       this.fkcodigoYearNew = fkcodigoYearNew;
    }
   
    public Integer getCodigoAuditoriaMes() {
        return this.codigoAuditoriaMes;
    }
    
    public void setCodigoAuditoriaMes(Integer codigoAuditoriaMes) {
        this.codigoAuditoriaMes = codigoAuditoriaMes;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreMesOld() {
        return this.nombreMesOld;
    }
    
    public void setNombreMesOld(String nombreMesOld) {
        this.nombreMesOld = nombreMesOld;
    }
    public Integer getFkcodigoYearOld() {
        return this.fkcodigoYearOld;
    }
    
    public void setFkcodigoYearOld(Integer fkcodigoYearOld) {
        this.fkcodigoYearOld = fkcodigoYearOld;
    }
    public String getNombreMesNew() {
        return this.nombreMesNew;
    }
    
    public void setNombreMesNew(String nombreMesNew) {
        this.nombreMesNew = nombreMesNew;
    }
    public Integer getFkcodigoYearNew() {
        return this.fkcodigoYearNew;
    }
    
    public void setFkcodigoYearNew(Integer fkcodigoYearNew) {
        this.fkcodigoYearNew = fkcodigoYearNew;
    }




}


