package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudiECliTienePedido generated by hbm2java
 */
public class AudiECliTienePedido  implements java.io.Serializable {


     private Integer codigoAudiECliTienePedido;
     private String usuario;
     private Date fechaCambio;
     private String nombreEstadoClienteTienePedidoOld;
     private byte[] fotoEstadoClienteTienePedidoOld;
     private Date versionOld;
     private String nombreEstadoClienteTienePedidoNew;
     private byte[] fotoEstadoClienteTienePedidoNew;
     private Date versionNew;

    public AudiECliTienePedido() {
    }

	
    public AudiECliTienePedido(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudiECliTienePedido(String usuario, Date fechaCambio, String nombreEstadoClienteTienePedidoOld, byte[] fotoEstadoClienteTienePedidoOld, Date versionOld, String nombreEstadoClienteTienePedidoNew, byte[] fotoEstadoClienteTienePedidoNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreEstadoClienteTienePedidoOld = nombreEstadoClienteTienePedidoOld;
       this.fotoEstadoClienteTienePedidoOld = fotoEstadoClienteTienePedidoOld;
       this.versionOld = versionOld;
       this.nombreEstadoClienteTienePedidoNew = nombreEstadoClienteTienePedidoNew;
       this.fotoEstadoClienteTienePedidoNew = fotoEstadoClienteTienePedidoNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiECliTienePedido() {
        return this.codigoAudiECliTienePedido;
    }
    
    public void setCodigoAudiECliTienePedido(Integer codigoAudiECliTienePedido) {
        this.codigoAudiECliTienePedido = codigoAudiECliTienePedido;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreEstadoClienteTienePedidoOld() {
        return this.nombreEstadoClienteTienePedidoOld;
    }
    
    public void setNombreEstadoClienteTienePedidoOld(String nombreEstadoClienteTienePedidoOld) {
        this.nombreEstadoClienteTienePedidoOld = nombreEstadoClienteTienePedidoOld;
    }
    public byte[] getFotoEstadoClienteTienePedidoOld() {
        return this.fotoEstadoClienteTienePedidoOld;
    }
    
    public void setFotoEstadoClienteTienePedidoOld(byte[] fotoEstadoClienteTienePedidoOld) {
        this.fotoEstadoClienteTienePedidoOld = fotoEstadoClienteTienePedidoOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreEstadoClienteTienePedidoNew() {
        return this.nombreEstadoClienteTienePedidoNew;
    }
    
    public void setNombreEstadoClienteTienePedidoNew(String nombreEstadoClienteTienePedidoNew) {
        this.nombreEstadoClienteTienePedidoNew = nombreEstadoClienteTienePedidoNew;
    }
    public byte[] getFotoEstadoClienteTienePedidoNew() {
        return this.fotoEstadoClienteTienePedidoNew;
    }
    
    public void setFotoEstadoClienteTienePedidoNew(byte[] fotoEstadoClienteTienePedidoNew) {
        this.fotoEstadoClienteTienePedidoNew = fotoEstadoClienteTienePedidoNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


