package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaPais generated by hbm2java
 */
public class AuditoriaPais  implements java.io.Serializable {


     private Integer codigoAudiPais;
     private String usuario;
     private Date fechaCambio;
     private String nombrePaisOld;
     private Date versionOld;
     private String nombrePaisNew;
     private Date versionNew;

    public AuditoriaPais() {
    }

	
    public AuditoriaPais(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaPais(String usuario, Date fechaCambio, String nombrePaisOld, Date versionOld, String nombrePaisNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombrePaisOld = nombrePaisOld;
       this.versionOld = versionOld;
       this.nombrePaisNew = nombrePaisNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiPais() {
        return this.codigoAudiPais;
    }
    
    public void setCodigoAudiPais(Integer codigoAudiPais) {
        this.codigoAudiPais = codigoAudiPais;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombrePaisOld() {
        return this.nombrePaisOld;
    }
    
    public void setNombrePaisOld(String nombrePaisOld) {
        this.nombrePaisOld = nombrePaisOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombrePaisNew() {
        return this.nombrePaisNew;
    }
    
    public void setNombrePaisNew(String nombrePaisNew) {
        this.nombrePaisNew = nombrePaisNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


