package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudiFacturaCTienePedido generated by hbm2java
 */
public class AudiFacturaCTienePedido  implements java.io.Serializable {


     private Integer codigoAudiFacturaClienteTienePedido;
     private String usuario;
     private Date fechaCambio;
     private String nombreFacturaClienteTienePedidoOld;
     private Date versionOld;
     private String nombreFacturaClienteTienePedidoNew;
     private Date versionNew;

    public AudiFacturaCTienePedido() {
    }

	
    public AudiFacturaCTienePedido(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudiFacturaCTienePedido(String usuario, Date fechaCambio, String nombreFacturaClienteTienePedidoOld, Date versionOld, String nombreFacturaClienteTienePedidoNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreFacturaClienteTienePedidoOld = nombreFacturaClienteTienePedidoOld;
       this.versionOld = versionOld;
       this.nombreFacturaClienteTienePedidoNew = nombreFacturaClienteTienePedidoNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiFacturaClienteTienePedido() {
        return this.codigoAudiFacturaClienteTienePedido;
    }
    
    public void setCodigoAudiFacturaClienteTienePedido(Integer codigoAudiFacturaClienteTienePedido) {
        this.codigoAudiFacturaClienteTienePedido = codigoAudiFacturaClienteTienePedido;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreFacturaClienteTienePedidoOld() {
        return this.nombreFacturaClienteTienePedidoOld;
    }
    
    public void setNombreFacturaClienteTienePedidoOld(String nombreFacturaClienteTienePedidoOld) {
        this.nombreFacturaClienteTienePedidoOld = nombreFacturaClienteTienePedidoOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreFacturaClienteTienePedidoNew() {
        return this.nombreFacturaClienteTienePedidoNew;
    }
    
    public void setNombreFacturaClienteTienePedidoNew(String nombreFacturaClienteTienePedidoNew) {
        this.nombreFacturaClienteTienePedidoNew = nombreFacturaClienteTienePedidoNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


