package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudiRecetaProducto generated by hbm2java
 */
public class AudiRecetaProducto  implements java.io.Serializable {


     private Integer codigoAudiRecetaProducto;
     private String usuario;
     private Date fechaCambio;
     private String modeloRecetaProductoOld;
     private Date fechaCreacionRecetaProductoOld;
     private Date versionOld;
     private String modeloRecetaProductoNew;
     private Date fechaCreacionRecetaProductoNew;
     private Date versionNew;

    public AudiRecetaProducto() {
    }

	
    public AudiRecetaProducto(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudiRecetaProducto(String usuario, Date fechaCambio, String modeloRecetaProductoOld, Date fechaCreacionRecetaProductoOld, Date versionOld, String modeloRecetaProductoNew, Date fechaCreacionRecetaProductoNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.modeloRecetaProductoOld = modeloRecetaProductoOld;
       this.fechaCreacionRecetaProductoOld = fechaCreacionRecetaProductoOld;
       this.versionOld = versionOld;
       this.modeloRecetaProductoNew = modeloRecetaProductoNew;
       this.fechaCreacionRecetaProductoNew = fechaCreacionRecetaProductoNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiRecetaProducto() {
        return this.codigoAudiRecetaProducto;
    }
    
    public void setCodigoAudiRecetaProducto(Integer codigoAudiRecetaProducto) {
        this.codigoAudiRecetaProducto = codigoAudiRecetaProducto;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getModeloRecetaProductoOld() {
        return this.modeloRecetaProductoOld;
    }
    
    public void setModeloRecetaProductoOld(String modeloRecetaProductoOld) {
        this.modeloRecetaProductoOld = modeloRecetaProductoOld;
    }
    public Date getFechaCreacionRecetaProductoOld() {
        return this.fechaCreacionRecetaProductoOld;
    }
    
    public void setFechaCreacionRecetaProductoOld(Date fechaCreacionRecetaProductoOld) {
        this.fechaCreacionRecetaProductoOld = fechaCreacionRecetaProductoOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getModeloRecetaProductoNew() {
        return this.modeloRecetaProductoNew;
    }
    
    public void setModeloRecetaProductoNew(String modeloRecetaProductoNew) {
        this.modeloRecetaProductoNew = modeloRecetaProductoNew;
    }
    public Date getFechaCreacionRecetaProductoNew() {
        return this.fechaCreacionRecetaProductoNew;
    }
    
    public void setFechaCreacionRecetaProductoNew(Date fechaCreacionRecetaProductoNew) {
        this.fechaCreacionRecetaProductoNew = fechaCreacionRecetaProductoNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


