package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AuditoriaDistrito generated by hbm2java
 */
public class AuditoriaDistrito  implements java.io.Serializable {


     private Integer codigoAudiDistrito;
     private String usuario;
     private Date fechaCambio;
     private Integer fkcodigoCiudadOld;
     private String nombreDistritoOld;
     private Date versionOld;
     private String fkcodigoCiudadNew;
     private String nombreDistritoNew;
     private Date versionNew;

    public AuditoriaDistrito() {
    }

	
    public AuditoriaDistrito(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AuditoriaDistrito(String usuario, Date fechaCambio, Integer fkcodigoCiudadOld, String nombreDistritoOld, Date versionOld, String fkcodigoCiudadNew, String nombreDistritoNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.fkcodigoCiudadOld = fkcodigoCiudadOld;
       this.nombreDistritoOld = nombreDistritoOld;
       this.versionOld = versionOld;
       this.fkcodigoCiudadNew = fkcodigoCiudadNew;
       this.nombreDistritoNew = nombreDistritoNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiDistrito() {
        return this.codigoAudiDistrito;
    }
    
    public void setCodigoAudiDistrito(Integer codigoAudiDistrito) {
        this.codigoAudiDistrito = codigoAudiDistrito;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public Integer getFkcodigoCiudadOld() {
        return this.fkcodigoCiudadOld;
    }
    
    public void setFkcodigoCiudadOld(Integer fkcodigoCiudadOld) {
        this.fkcodigoCiudadOld = fkcodigoCiudadOld;
    }
    public String getNombreDistritoOld() {
        return this.nombreDistritoOld;
    }
    
    public void setNombreDistritoOld(String nombreDistritoOld) {
        this.nombreDistritoOld = nombreDistritoOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getFkcodigoCiudadNew() {
        return this.fkcodigoCiudadNew;
    }
    
    public void setFkcodigoCiudadNew(String fkcodigoCiudadNew) {
        this.fkcodigoCiudadNew = fkcodigoCiudadNew;
    }
    public String getNombreDistritoNew() {
        return this.nombreDistritoNew;
    }
    
    public void setNombreDistritoNew(String nombreDistritoNew) {
        this.nombreDistritoNew = nombreDistritoNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


