package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AudLoteInsumo generated by hbm2java
 */
public class AudLoteInsumo  implements java.io.Serializable {


     private Integer codigoAudiLoteInsumo;
     private String usuario;
     private Date fechaCambio;
     private String nombreLoteInsumoOld;
     private Date versionOld;
     private String nombreLoteInsumoNew;
     private Date versionNew;

    public AudLoteInsumo() {
    }

	
    public AudLoteInsumo(String usuario, Date fechaCambio) {
        this.usuario = usuario;
        this.fechaCambio = fechaCambio;
    }
    public AudLoteInsumo(String usuario, Date fechaCambio, String nombreLoteInsumoOld, Date versionOld, String nombreLoteInsumoNew, Date versionNew) {
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.nombreLoteInsumoOld = nombreLoteInsumoOld;
       this.versionOld = versionOld;
       this.nombreLoteInsumoNew = nombreLoteInsumoNew;
       this.versionNew = versionNew;
    }
   
    public Integer getCodigoAudiLoteInsumo() {
        return this.codigoAudiLoteInsumo;
    }
    
    public void setCodigoAudiLoteInsumo(Integer codigoAudiLoteInsumo) {
        this.codigoAudiLoteInsumo = codigoAudiLoteInsumo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getNombreLoteInsumoOld() {
        return this.nombreLoteInsumoOld;
    }
    
    public void setNombreLoteInsumoOld(String nombreLoteInsumoOld) {
        this.nombreLoteInsumoOld = nombreLoteInsumoOld;
    }
    public Date getVersionOld() {
        return this.versionOld;
    }
    
    public void setVersionOld(Date versionOld) {
        this.versionOld = versionOld;
    }
    public String getNombreLoteInsumoNew() {
        return this.nombreLoteInsumoNew;
    }
    
    public void setNombreLoteInsumoNew(String nombreLoteInsumoNew) {
        this.nombreLoteInsumoNew = nombreLoteInsumoNew;
    }
    public Date getVersionNew() {
        return this.versionNew;
    }
    
    public void setVersionNew(Date versionNew) {
        this.versionNew = versionNew;
    }




}


