package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Catalogo generated by hbm2java
 */
public class Catalogo  implements java.io.Serializable {


     private Integer codigoCatalogo;
     private Date version;
     private EstadoCatalogo estadoCatalogo;
     private Integer catCodigoProducto;
     private String catNombreProducto;
     private String catNombreTipoProducto;
     private Float catTiempoenhornoTipoProducto;
     private Float catTemperaturaenhornoTipoProducto;
     private Float catValorNeto;
     private Float catValorConIgv;
     private byte[] catFotoProducto;
     private String catPreparacionProducto;
     private String catColoresProducto;
     private String catNombreInsumo;
     private String catModeloRecetaProducto;
     private Integer cantidadMasPedido;
     private Float promedioTotalProd;

    public Catalogo() {
    }

    public Catalogo(EstadoCatalogo estadoCatalogo, Integer catCodigoProducto, String catNombreProducto, String catNombreTipoProducto, Float catTiempoenhornoTipoProducto, Float catTemperaturaenhornoTipoProducto, Float catValorNeto, Float catValorConIgv, byte[] catFotoProducto, String catPreparacionProducto, String catColoresProducto, String catNombreInsumo, String catModeloRecetaProducto, Integer cantidadMasPedido, Float promedioTotalProd) {
       this.estadoCatalogo = estadoCatalogo;
       this.catCodigoProducto = catCodigoProducto;
       this.catNombreProducto = catNombreProducto;
       this.catNombreTipoProducto = catNombreTipoProducto;
       this.catTiempoenhornoTipoProducto = catTiempoenhornoTipoProducto;
       this.catTemperaturaenhornoTipoProducto = catTemperaturaenhornoTipoProducto;
       this.catValorNeto = catValorNeto;
       this.catValorConIgv = catValorConIgv;
       this.catFotoProducto = catFotoProducto;
       this.catPreparacionProducto = catPreparacionProducto;
       this.catColoresProducto = catColoresProducto;
       this.catNombreInsumo = catNombreInsumo;
       this.catModeloRecetaProducto = catModeloRecetaProducto;
       this.cantidadMasPedido = cantidadMasPedido;
       this.promedioTotalProd = promedioTotalProd;
    }
   
    public Integer getCodigoCatalogo() {
        return this.codigoCatalogo;
    }
    
    public void setCodigoCatalogo(Integer codigoCatalogo) {
        this.codigoCatalogo = codigoCatalogo;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public EstadoCatalogo getEstadoCatalogo() {
        return this.estadoCatalogo;
    }
    
    public void setEstadoCatalogo(EstadoCatalogo estadoCatalogo) {
        this.estadoCatalogo = estadoCatalogo;
    }
    public Integer getCatCodigoProducto() {
        return this.catCodigoProducto;
    }
    
    public void setCatCodigoProducto(Integer catCodigoProducto) {
        this.catCodigoProducto = catCodigoProducto;
    }
    public String getCatNombreProducto() {
        return this.catNombreProducto;
    }
    
    public void setCatNombreProducto(String catNombreProducto) {
        this.catNombreProducto = catNombreProducto;
    }
    public String getCatNombreTipoProducto() {
        return this.catNombreTipoProducto;
    }
    
    public void setCatNombreTipoProducto(String catNombreTipoProducto) {
        this.catNombreTipoProducto = catNombreTipoProducto;
    }
    public Float getCatTiempoenhornoTipoProducto() {
        return this.catTiempoenhornoTipoProducto;
    }
    
    public void setCatTiempoenhornoTipoProducto(Float catTiempoenhornoTipoProducto) {
        this.catTiempoenhornoTipoProducto = catTiempoenhornoTipoProducto;
    }
    public Float getCatTemperaturaenhornoTipoProducto() {
        return this.catTemperaturaenhornoTipoProducto;
    }
    
    public void setCatTemperaturaenhornoTipoProducto(Float catTemperaturaenhornoTipoProducto) {
        this.catTemperaturaenhornoTipoProducto = catTemperaturaenhornoTipoProducto;
    }
    public Float getCatValorNeto() {
        return this.catValorNeto;
    }
    
    public void setCatValorNeto(Float catValorNeto) {
        this.catValorNeto = catValorNeto;
    }
    public Float getCatValorConIgv() {
        return this.catValorConIgv;
    }
    
    public void setCatValorConIgv(Float catValorConIgv) {
        this.catValorConIgv = catValorConIgv;
    }
    public byte[] getCatFotoProducto() {
        return this.catFotoProducto;
    }
    
    public void setCatFotoProducto(byte[] catFotoProducto) {
        this.catFotoProducto = catFotoProducto;
    }
    public String getCatPreparacionProducto() {
        return this.catPreparacionProducto;
    }
    
    public void setCatPreparacionProducto(String catPreparacionProducto) {
        this.catPreparacionProducto = catPreparacionProducto;
    }
    public String getCatColoresProducto() {
        return this.catColoresProducto;
    }
    
    public void setCatColoresProducto(String catColoresProducto) {
        this.catColoresProducto = catColoresProducto;
    }
    public String getCatNombreInsumo() {
        return this.catNombreInsumo;
    }
    
    public void setCatNombreInsumo(String catNombreInsumo) {
        this.catNombreInsumo = catNombreInsumo;
    }
    public String getCatModeloRecetaProducto() {
        return this.catModeloRecetaProducto;
    }
    
    public void setCatModeloRecetaProducto(String catModeloRecetaProducto) {
        this.catModeloRecetaProducto = catModeloRecetaProducto;
    }
    public Integer getCantidadMasPedido() {
        return this.cantidadMasPedido;
    }
    
    public void setCantidadMasPedido(Integer cantidadMasPedido) {
        this.cantidadMasPedido = cantidadMasPedido;
    }
    public Float getPromedioTotalProd() {
        return this.promedioTotalProd;
    }
    
    public void setPromedioTotalProd(Float promedioTotalProd) {
        this.promedioTotalProd = promedioTotalProd;
    }




}


