package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codigoCliente;
     private Date version;
     private EstadoCliente estadoCliente;
     private RegimenCliente regimenCliente;
     private Usuario usuario;
     private String razonsocialCliente;
     private Float latitudCliente;
     private Float longitudCliente;
     private String typeCliente;
     private byte[] fotoUbicacionCliente;
     private String rucCliente;
     private String dniCliente;
     private Date fechaEmpadronamientoCliente;
     private Set<ClienteTienePedido> clienteTienePedidos = new HashSet<ClienteTienePedido>(0);
     private Set<ClienteTienePreferencia> clienteTienePreferencias = new HashSet<ClienteTienePreferencia>(0);

    public Cliente() {
    }

    public Cliente(EstadoCliente estadoCliente, RegimenCliente regimenCliente, Usuario usuario, String razonsocialCliente, Float latitudCliente, Float longitudCliente, String typeCliente, byte[] fotoUbicacionCliente, String rucCliente, String dniCliente, Date fechaEmpadronamientoCliente, Set<ClienteTienePedido> clienteTienePedidos, Set<ClienteTienePreferencia> clienteTienePreferencias) {
       this.estadoCliente = estadoCliente;
       this.regimenCliente = regimenCliente;
       this.usuario = usuario;
       this.razonsocialCliente = razonsocialCliente;
       this.latitudCliente = latitudCliente;
       this.longitudCliente = longitudCliente;
       this.typeCliente = typeCliente;
       this.fotoUbicacionCliente = fotoUbicacionCliente;
       this.rucCliente = rucCliente;
       this.dniCliente = dniCliente;
       this.fechaEmpadronamientoCliente = fechaEmpadronamientoCliente;
       this.clienteTienePedidos = clienteTienePedidos;
       this.clienteTienePreferencias = clienteTienePreferencias;
    }
   
    public Integer getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(Integer codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public EstadoCliente getEstadoCliente() {
        return this.estadoCliente;
    }
    
    public void setEstadoCliente(EstadoCliente estadoCliente) {
        this.estadoCliente = estadoCliente;
    }
    public RegimenCliente getRegimenCliente() {
        return this.regimenCliente;
    }
    
    public void setRegimenCliente(RegimenCliente regimenCliente) {
        this.regimenCliente = regimenCliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRazonsocialCliente() {
        return this.razonsocialCliente;
    }
    
    public void setRazonsocialCliente(String razonsocialCliente) {
        this.razonsocialCliente = razonsocialCliente;
    }
    public Float getLatitudCliente() {
        return this.latitudCliente;
    }
    
    public void setLatitudCliente(Float latitudCliente) {
        this.latitudCliente = latitudCliente;
    }
    public Float getLongitudCliente() {
        return this.longitudCliente;
    }
    
    public void setLongitudCliente(Float longitudCliente) {
        this.longitudCliente = longitudCliente;
    }
    public String getTypeCliente() {
        return this.typeCliente;
    }
    
    public void setTypeCliente(String typeCliente) {
        this.typeCliente = typeCliente;
    }
    public byte[] getFotoUbicacionCliente() {
        return this.fotoUbicacionCliente;
    }
    
    public void setFotoUbicacionCliente(byte[] fotoUbicacionCliente) {
        this.fotoUbicacionCliente = fotoUbicacionCliente;
    }
    public String getRucCliente() {
        return this.rucCliente;
    }
    
    public void setRucCliente(String rucCliente) {
        this.rucCliente = rucCliente;
    }
    public String getDniCliente() {
        return this.dniCliente;
    }
    
    public void setDniCliente(String dniCliente) {
        this.dniCliente = dniCliente;
    }
    public Date getFechaEmpadronamientoCliente() {
        return this.fechaEmpadronamientoCliente;
    }
    
    public void setFechaEmpadronamientoCliente(Date fechaEmpadronamientoCliente) {
        this.fechaEmpadronamientoCliente = fechaEmpadronamientoCliente;
    }
    public Set<ClienteTienePedido> getClienteTienePedidos() {
        return this.clienteTienePedidos;
    }
    
    public void setClienteTienePedidos(Set<ClienteTienePedido> clienteTienePedidos) {
        this.clienteTienePedidos = clienteTienePedidos;
    }
    public Set<ClienteTienePreferencia> getClienteTienePreferencias() {
        return this.clienteTienePreferencias;
    }
    
    public void setClienteTienePreferencias(Set<ClienteTienePreferencia> clienteTienePreferencias) {
        this.clienteTienePreferencias = clienteTienePreferencias;
    }




}


