package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ClienteTienePreferencia generated by hbm2java
 */
public class ClienteTienePreferencia  implements java.io.Serializable {


     private Integer codigoPreferenciaSku;
     private Date version;
     private Cliente cliente;
     private Producto producto;
     private Date fechaVotoPreferencia;
     private Float cantidadPuntos;

    public ClienteTienePreferencia() {
    }

    public ClienteTienePreferencia(Cliente cliente, Producto producto, Date fechaVotoPreferencia, Float cantidadPuntos) {
       this.cliente = cliente;
       this.producto = producto;
       this.fechaVotoPreferencia = fechaVotoPreferencia;
       this.cantidadPuntos = cantidadPuntos;
    }
   
    public Integer getCodigoPreferenciaSku() {
        return this.codigoPreferenciaSku;
    }
    
    public void setCodigoPreferenciaSku(Integer codigoPreferenciaSku) {
        this.codigoPreferenciaSku = codigoPreferenciaSku;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getFechaVotoPreferencia() {
        return this.fechaVotoPreferencia;
    }
    
    public void setFechaVotoPreferencia(Date fechaVotoPreferencia) {
        this.fechaVotoPreferencia = fechaVotoPreferencia;
    }
    public Float getCantidadPuntos() {
        return this.cantidadPuntos;
    }
    
    public void setCantidadPuntos(Float cantidadPuntos) {
        this.cantidadPuntos = cantidadPuntos;
    }




}


