package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CplTieneZtd generated by hbm2java
 */
public class CplTieneZtd  implements java.io.Serializable {


     private Integer codigoCplTieneZtd;
     private Date version;
     private CuotaPorLinea cuotaPorLinea;
     private ZonaTieneDistrito zonaTieneDistrito;
     private Float cuotaAsignada;
     private Float cuotaRealizada;

    public CplTieneZtd() {
    }

    public CplTieneZtd(CuotaPorLinea cuotaPorLinea, ZonaTieneDistrito zonaTieneDistrito, Float cuotaAsignada, Float cuotaRealizada) {
       this.cuotaPorLinea = cuotaPorLinea;
       this.zonaTieneDistrito = zonaTieneDistrito;
       this.cuotaAsignada = cuotaAsignada;
       this.cuotaRealizada = cuotaRealizada;
    }
   
    public Integer getCodigoCplTieneZtd() {
        return this.codigoCplTieneZtd;
    }
    
    public void setCodigoCplTieneZtd(Integer codigoCplTieneZtd) {
        this.codigoCplTieneZtd = codigoCplTieneZtd;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public CuotaPorLinea getCuotaPorLinea() {
        return this.cuotaPorLinea;
    }
    
    public void setCuotaPorLinea(CuotaPorLinea cuotaPorLinea) {
        this.cuotaPorLinea = cuotaPorLinea;
    }
    public ZonaTieneDistrito getZonaTieneDistrito() {
        return this.zonaTieneDistrito;
    }
    
    public void setZonaTieneDistrito(ZonaTieneDistrito zonaTieneDistrito) {
        this.zonaTieneDistrito = zonaTieneDistrito;
    }
    public Float getCuotaAsignada() {
        return this.cuotaAsignada;
    }
    
    public void setCuotaAsignada(Float cuotaAsignada) {
        this.cuotaAsignada = cuotaAsignada;
    }
    public Float getCuotaRealizada() {
        return this.cuotaRealizada;
    }
    
    public void setCuotaRealizada(Float cuotaRealizada) {
        this.cuotaRealizada = cuotaRealizada;
    }




}


