package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cuota generated by hbm2java
 */
public class Cuota  implements java.io.Serializable {


     private Integer codigoCuota;
     private Date version;
     private Mes mes;
     private Producto producto;
     private Float montoCuota;

    public Cuota() {
    }

    public Cuota(Mes mes, Producto producto, Float montoCuota) {
       this.mes = mes;
       this.producto = producto;
       this.montoCuota = montoCuota;
    }
   
    public Integer getCodigoCuota() {
        return this.codigoCuota;
    }
    
    public void setCodigoCuota(Integer codigoCuota) {
        this.codigoCuota = codigoCuota;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public Mes getMes() {
        return this.mes;
    }
    
    public void setMes(Mes mes) {
        this.mes = mes;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Float getMontoCuota() {
        return this.montoCuota;
    }
    
    public void setMontoCuota(Float montoCuota) {
        this.montoCuota = montoCuota;
    }




}


