package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1



/**
 * Cuota generated by hbm2java
 */
public class Cuota  implements java.io.Serializable {


     private Integer codigoCuota;
     private Mes mes;
     private Producto producto;
     private Float montoCuota;

    public Cuota() {
    }

    public Cuota(Mes mes, Producto producto, Float montoCuota) {
       this.mes = mes;
       this.producto = producto;
       this.montoCuota = montoCuota;
    }
   
    public Integer getCodigoCuota() {
        return this.codigoCuota;
    }
    
    public void setCodigoCuota(Integer codigoCuota) {
        this.codigoCuota = codigoCuota;
    }
    public Mes getMes() {
        return this.mes;
    }
    
    public void setMes(Mes mes) {
        this.mes = mes;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Float getMontoCuota() {
        return this.montoCuota;
    }
    
    public void setMontoCuota(Float montoCuota) {
        this.montoCuota = montoCuota;
    }




}


