package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Distrito generated by hbm2java
 */
public class Distrito  implements java.io.Serializable {


     private Integer codigoDistrito;
     private Ciudad ciudad;
     private String nombreDistrito;
     private Set<ZonaTieneDistrito> zonaTieneDistritos = new HashSet<ZonaTieneDistrito>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Distrito() {
    }

    public Distrito(Ciudad ciudad, String nombreDistrito, Set<ZonaTieneDistrito> zonaTieneDistritos, Set<Usuario> usuarios) {
       this.ciudad = ciudad;
       this.nombreDistrito = nombreDistrito;
       this.zonaTieneDistritos = zonaTieneDistritos;
       this.usuarios = usuarios;
    }
   
    public Integer getCodigoDistrito() {
        return this.codigoDistrito;
    }
    
    public void setCodigoDistrito(Integer codigoDistrito) {
        this.codigoDistrito = codigoDistrito;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public String getNombreDistrito() {
        return this.nombreDistrito;
    }
    
    public void setNombreDistrito(String nombreDistrito) {
        this.nombreDistrito = nombreDistrito;
    }
    public Set<ZonaTieneDistrito> getZonaTieneDistritos() {
        return this.zonaTieneDistritos;
    }
    
    public void setZonaTieneDistritos(Set<ZonaTieneDistrito> zonaTieneDistritos) {
        this.zonaTieneDistritos = zonaTieneDistritos;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


