package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoCliente generated by hbm2java
 */
public class EstadoCliente  implements java.io.Serializable {


     private Integer codigoEstadoCliente;
     private String nombreEstadoCliente;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public EstadoCliente() {
    }

	
    public EstadoCliente(String nombreEstadoCliente) {
        this.nombreEstadoCliente = nombreEstadoCliente;
    }
    public EstadoCliente(String nombreEstadoCliente, Set<Cliente> clientes) {
       this.nombreEstadoCliente = nombreEstadoCliente;
       this.clientes = clientes;
    }
   
    public Integer getCodigoEstadoCliente() {
        return this.codigoEstadoCliente;
    }
    
    public void setCodigoEstadoCliente(Integer codigoEstadoCliente) {
        this.codigoEstadoCliente = codigoEstadoCliente;
    }
    public String getNombreEstadoCliente() {
        return this.nombreEstadoCliente;
    }
    
    public void setNombreEstadoCliente(String nombreEstadoCliente) {
        this.nombreEstadoCliente = nombreEstadoCliente;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


