package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoProducto generated by hbm2java
 */
public class EstadoProducto  implements java.io.Serializable {


     private Integer codigoEstadoProducto;
     private String nombreEstadoProducto;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public EstadoProducto() {
    }

    public EstadoProducto(String nombreEstadoProducto, Set<Producto> productos) {
       this.nombreEstadoProducto = nombreEstadoProducto;
       this.productos = productos;
    }
   
    public Integer getCodigoEstadoProducto() {
        return this.codigoEstadoProducto;
    }
    
    public void setCodigoEstadoProducto(Integer codigoEstadoProducto) {
        this.codigoEstadoProducto = codigoEstadoProducto;
    }
    public String getNombreEstadoProducto() {
        return this.nombreEstadoProducto;
    }
    
    public void setNombreEstadoProducto(String nombreEstadoProducto) {
        this.nombreEstadoProducto = nombreEstadoProducto;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


