package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoClienteTienePedido generated by hbm2java
 */
public class EstadoClienteTienePedido  implements java.io.Serializable {


     private Integer codigoEstadoClienteTienePedido;
     private String nombreEstadoClienteTienePedido;
     private byte[] fotoEstadoClienteTienePedido;
     private Set<ClienteTienePedido> clienteTienePedidos = new HashSet<ClienteTienePedido>(0);

    public EstadoClienteTienePedido() {
    }

    public EstadoClienteTienePedido(String nombreEstadoClienteTienePedido, byte[] fotoEstadoClienteTienePedido, Set<ClienteTienePedido> clienteTienePedidos) {
       this.nombreEstadoClienteTienePedido = nombreEstadoClienteTienePedido;
       this.fotoEstadoClienteTienePedido = fotoEstadoClienteTienePedido;
       this.clienteTienePedidos = clienteTienePedidos;
    }
   
    public Integer getCodigoEstadoClienteTienePedido() {
        return this.codigoEstadoClienteTienePedido;
    }
    
    public void setCodigoEstadoClienteTienePedido(Integer codigoEstadoClienteTienePedido) {
        this.codigoEstadoClienteTienePedido = codigoEstadoClienteTienePedido;
    }
    public String getNombreEstadoClienteTienePedido() {
        return this.nombreEstadoClienteTienePedido;
    }
    
    public void setNombreEstadoClienteTienePedido(String nombreEstadoClienteTienePedido) {
        this.nombreEstadoClienteTienePedido = nombreEstadoClienteTienePedido;
    }
    public byte[] getFotoEstadoClienteTienePedido() {
        return this.fotoEstadoClienteTienePedido;
    }
    
    public void setFotoEstadoClienteTienePedido(byte[] fotoEstadoClienteTienePedido) {
        this.fotoEstadoClienteTienePedido = fotoEstadoClienteTienePedido;
    }
    public Set<ClienteTienePedido> getClienteTienePedidos() {
        return this.clienteTienePedidos;
    }
    
    public void setClienteTienePedidos(Set<ClienteTienePedido> clienteTienePedidos) {
        this.clienteTienePedidos = clienteTienePedidos;
    }




}


