package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EstadoInsumo generated by hbm2java
 */
public class EstadoInsumo  implements java.io.Serializable {


     private Integer codigoEstadoInsumo;
     private Date version;
     private String nombreEstadoInsumo;
     private Set<Insumo> insumos = new HashSet<Insumo>(0);

    public EstadoInsumo() {
    }

    public EstadoInsumo(String nombreEstadoInsumo, Set<Insumo> insumos) {
       this.nombreEstadoInsumo = nombreEstadoInsumo;
       this.insumos = insumos;
    }
   
    public Integer getCodigoEstadoInsumo() {
        return this.codigoEstadoInsumo;
    }
    
    public void setCodigoEstadoInsumo(Integer codigoEstadoInsumo) {
        this.codigoEstadoInsumo = codigoEstadoInsumo;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public String getNombreEstadoInsumo() {
        return this.nombreEstadoInsumo;
    }
    
    public void setNombreEstadoInsumo(String nombreEstadoInsumo) {
        this.nombreEstadoInsumo = nombreEstadoInsumo;
    }
    public Set<Insumo> getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Set<Insumo> insumos) {
        this.insumos = insumos;
    }




}


