package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FacturaCTienePedido generated by hbm2java
 */
public class FacturaCTienePedido  implements java.io.Serializable {


     private Integer codigoFacturaClienteTienePedido;
     private String nombreFacturaClienteTienePedido;
     private Set<ClienteTienePedido> clienteTienePedidos = new HashSet<ClienteTienePedido>(0);

    public FacturaCTienePedido() {
    }

    public FacturaCTienePedido(String nombreFacturaClienteTienePedido, Set<ClienteTienePedido> clienteTienePedidos) {
       this.nombreFacturaClienteTienePedido = nombreFacturaClienteTienePedido;
       this.clienteTienePedidos = clienteTienePedidos;
    }
   
    public Integer getCodigoFacturaClienteTienePedido() {
        return this.codigoFacturaClienteTienePedido;
    }
    
    public void setCodigoFacturaClienteTienePedido(Integer codigoFacturaClienteTienePedido) {
        this.codigoFacturaClienteTienePedido = codigoFacturaClienteTienePedido;
    }
    public String getNombreFacturaClienteTienePedido() {
        return this.nombreFacturaClienteTienePedido;
    }
    
    public void setNombreFacturaClienteTienePedido(String nombreFacturaClienteTienePedido) {
        this.nombreFacturaClienteTienePedido = nombreFacturaClienteTienePedido;
    }
    public Set<ClienteTienePedido> getClienteTienePedidos() {
        return this.clienteTienePedidos;
    }
    
    public void setClienteTienePedidos(Set<ClienteTienePedido> clienteTienePedidos) {
        this.clienteTienePedidos = clienteTienePedidos;
    }




}


