package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Insumo generated by hbm2java
 */
public class Insumo  implements java.io.Serializable {


     private Integer codigoInsumo;
     private String nombreInsumo;
     private String marcaInsumo;
     private Date fechaIngresoInsumo;
     private Float pesoInsumo;
     private String presentacionInsumo;
     private Float precioUnitarioInsumo;
     private Set<RecetaProductoTieneInsumo> recetaProductoTieneInsumos = new HashSet<RecetaProductoTieneInsumo>(0);

    public Insumo() {
    }

    public Insumo(String nombreInsumo, String marcaInsumo, Date fechaIngresoInsumo, Float pesoInsumo, String presentacionInsumo, Float precioUnitarioInsumo, Set<RecetaProductoTieneInsumo> recetaProductoTieneInsumos) {
       this.nombreInsumo = nombreInsumo;
       this.marcaInsumo = marcaInsumo;
       this.fechaIngresoInsumo = fechaIngresoInsumo;
       this.pesoInsumo = pesoInsumo;
       this.presentacionInsumo = presentacionInsumo;
       this.precioUnitarioInsumo = precioUnitarioInsumo;
       this.recetaProductoTieneInsumos = recetaProductoTieneInsumos;
    }
   
    public Integer getCodigoInsumo() {
        return this.codigoInsumo;
    }
    
    public void setCodigoInsumo(Integer codigoInsumo) {
        this.codigoInsumo = codigoInsumo;
    }
    public String getNombreInsumo() {
        return this.nombreInsumo;
    }
    
    public void setNombreInsumo(String nombreInsumo) {
        this.nombreInsumo = nombreInsumo;
    }
    public String getMarcaInsumo() {
        return this.marcaInsumo;
    }
    
    public void setMarcaInsumo(String marcaInsumo) {
        this.marcaInsumo = marcaInsumo;
    }
    public Date getFechaIngresoInsumo() {
        return this.fechaIngresoInsumo;
    }
    
    public void setFechaIngresoInsumo(Date fechaIngresoInsumo) {
        this.fechaIngresoInsumo = fechaIngresoInsumo;
    }
    public Float getPesoInsumo() {
        return this.pesoInsumo;
    }
    
    public void setPesoInsumo(Float pesoInsumo) {
        this.pesoInsumo = pesoInsumo;
    }
    public String getPresentacionInsumo() {
        return this.presentacionInsumo;
    }
    
    public void setPresentacionInsumo(String presentacionInsumo) {
        this.presentacionInsumo = presentacionInsumo;
    }
    public Float getPrecioUnitarioInsumo() {
        return this.precioUnitarioInsumo;
    }
    
    public void setPrecioUnitarioInsumo(Float precioUnitarioInsumo) {
        this.precioUnitarioInsumo = precioUnitarioInsumo;
    }
    public Set<RecetaProductoTieneInsumo> getRecetaProductoTieneInsumos() {
        return this.recetaProductoTieneInsumos;
    }
    
    public void setRecetaProductoTieneInsumos(Set<RecetaProductoTieneInsumo> recetaProductoTieneInsumos) {
        this.recetaProductoTieneInsumos = recetaProductoTieneInsumos;
    }




}


