package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Linea generated by hbm2java
 */
public class Linea  implements java.io.Serializable {


     private Integer codigoLinea;
     private String nombreLinea;
     private byte[] iconoLinea;
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<CuotaPorLinea> cuotaPorLineas = new HashSet<CuotaPorLinea>(0);

    public Linea() {
    }

    public Linea(String nombreLinea, byte[] iconoLinea, Set<Producto> productos, Set<CuotaPorLinea> cuotaPorLineas) {
       this.nombreLinea = nombreLinea;
       this.iconoLinea = iconoLinea;
       this.productos = productos;
       this.cuotaPorLineas = cuotaPorLineas;
    }
   
    public Integer getCodigoLinea() {
        return this.codigoLinea;
    }
    
    public void setCodigoLinea(Integer codigoLinea) {
        this.codigoLinea = codigoLinea;
    }
    public String getNombreLinea() {
        return this.nombreLinea;
    }
    
    public void setNombreLinea(String nombreLinea) {
        this.nombreLinea = nombreLinea;
    }
    public byte[] getIconoLinea() {
        return this.iconoLinea;
    }
    
    public void setIconoLinea(byte[] iconoLinea) {
        this.iconoLinea = iconoLinea;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
    public Set<CuotaPorLinea> getCuotaPorLineas() {
        return this.cuotaPorLineas;
    }
    
    public void setCuotaPorLineas(Set<CuotaPorLinea> cuotaPorLineas) {
        this.cuotaPorLineas = cuotaPorLineas;
    }




}


