package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LoteInsumo generated by hbm2java
 */
public class LoteInsumo  implements java.io.Serializable {


     private Integer codigoLoteInsumo;
     private Date version;
     private String nombreLoteInsumo;
     private Set<Insumo> insumos = new HashSet<Insumo>(0);

    public LoteInsumo() {
    }

    public LoteInsumo(String nombreLoteInsumo, Set<Insumo> insumos) {
       this.nombreLoteInsumo = nombreLoteInsumo;
       this.insumos = insumos;
    }
   
    public Integer getCodigoLoteInsumo() {
        return this.codigoLoteInsumo;
    }
    
    public void setCodigoLoteInsumo(Integer codigoLoteInsumo) {
        this.codigoLoteInsumo = codigoLoteInsumo;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public String getNombreLoteInsumo() {
        return this.nombreLoteInsumo;
    }
    
    public void setNombreLoteInsumo(String nombreLoteInsumo) {
        this.nombreLoteInsumo = nombreLoteInsumo;
    }
    public Set<Insumo> getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Set<Insumo> insumos) {
        this.insumos = insumos;
    }




}


