package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mes generated by hbm2java
 */
public class Mes  implements java.io.Serializable {


     private Integer codigoMes;
     private Date version;
     private Year year;
     private String nombreMes;
     private Set<Cuota> cuotas = new HashSet<Cuota>(0);
     private Set<CuotaPorLinea> cuotaPorLineas = new HashSet<CuotaPorLinea>(0);

    public Mes() {
    }

    public Mes(Year year, String nombreMes, Set<Cuota> cuotas, Set<CuotaPorLinea> cuotaPorLineas) {
       this.year = year;
       this.nombreMes = nombreMes;
       this.cuotas = cuotas;
       this.cuotaPorLineas = cuotaPorLineas;
    }
   
    public Integer getCodigoMes() {
        return this.codigoMes;
    }
    
    public void setCodigoMes(Integer codigoMes) {
        this.codigoMes = codigoMes;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public Year getYear() {
        return this.year;
    }
    
    public void setYear(Year year) {
        this.year = year;
    }
    public String getNombreMes() {
        return this.nombreMes;
    }
    
    public void setNombreMes(String nombreMes) {
        this.nombreMes = nombreMes;
    }
    public Set<Cuota> getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(Set<Cuota> cuotas) {
        this.cuotas = cuotas;
    }
    public Set<CuotaPorLinea> getCuotaPorLineas() {
        return this.cuotaPorLineas;
    }
    
    public void setCuotaPorLineas(Set<CuotaPorLinea> cuotaPorLineas) {
        this.cuotaPorLineas = cuotaPorLineas;
    }




}


