package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer codigoPais;
     private String nombrePais;
     private Set<Provincia> provincias = new HashSet<Provincia>(0);

    public Pais() {
    }

	
    public Pais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Pais(String nombrePais, Set<Provincia> provincias) {
       this.nombrePais = nombrePais;
       this.provincias = provincias;
    }
   
    public Integer getCodigoPais() {
        return this.codigoPais;
    }
    
    public void setCodigoPais(Integer codigoPais) {
        this.codigoPais = codigoPais;
    }
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Set<Provincia> getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set<Provincia> provincias) {
        this.provincias = provincias;
    }




}


