package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PresentacionInsumo generated by hbm2java
 */
public class PresentacionInsumo  implements java.io.Serializable {


     private Integer codigoPresentacionInsumo;
     private Date version;
     private String nombrePresentacionInsumo;
     private Set<Insumo> insumos = new HashSet<Insumo>(0);

    public PresentacionInsumo() {
    }

    public PresentacionInsumo(String nombrePresentacionInsumo, Set<Insumo> insumos) {
       this.nombrePresentacionInsumo = nombrePresentacionInsumo;
       this.insumos = insumos;
    }
   
    public Integer getCodigoPresentacionInsumo() {
        return this.codigoPresentacionInsumo;
    }
    
    public void setCodigoPresentacionInsumo(Integer codigoPresentacionInsumo) {
        this.codigoPresentacionInsumo = codigoPresentacionInsumo;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public String getNombrePresentacionInsumo() {
        return this.nombrePresentacionInsumo;
    }
    
    public void setNombrePresentacionInsumo(String nombrePresentacionInsumo) {
        this.nombrePresentacionInsumo = nombrePresentacionInsumo;
    }
    public Set<Insumo> getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Set<Insumo> insumos) {
        this.insumos = insumos;
    }




}


