package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1



/**
 * ProductoPorPedido generated by hbm2java
 */
public class ProductoPorPedido  implements java.io.Serializable {


     private Integer codigoProductoPorPedido;
     private ClienteTienePedido clienteTienePedido;
     private Producto producto;
     private Float descuentoPromocion;
     private Float valorNeto;
     private Float valorConIgv;
     private Integer cantidadProducto;

    public ProductoPorPedido() {
    }

    public ProductoPorPedido(ClienteTienePedido clienteTienePedido, Producto producto, Float descuentoPromocion, Float valorNeto, Float valorConIgv, Integer cantidadProducto) {
       this.clienteTienePedido = clienteTienePedido;
       this.producto = producto;
       this.descuentoPromocion = descuentoPromocion;
       this.valorNeto = valorNeto;
       this.valorConIgv = valorConIgv;
       this.cantidadProducto = cantidadProducto;
    }
   
    public Integer getCodigoProductoPorPedido() {
        return this.codigoProductoPorPedido;
    }
    
    public void setCodigoProductoPorPedido(Integer codigoProductoPorPedido) {
        this.codigoProductoPorPedido = codigoProductoPorPedido;
    }
    public ClienteTienePedido getClienteTienePedido() {
        return this.clienteTienePedido;
    }
    
    public void setClienteTienePedido(ClienteTienePedido clienteTienePedido) {
        this.clienteTienePedido = clienteTienePedido;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Float getDescuentoPromocion() {
        return this.descuentoPromocion;
    }
    
    public void setDescuentoPromocion(Float descuentoPromocion) {
        this.descuentoPromocion = descuentoPromocion;
    }
    public Float getValorNeto() {
        return this.valorNeto;
    }
    
    public void setValorNeto(Float valorNeto) {
        this.valorNeto = valorNeto;
    }
    public Float getValorConIgv() {
        return this.valorConIgv;
    }
    
    public void setValorConIgv(Float valorConIgv) {
        this.valorConIgv = valorConIgv;
    }
    public Integer getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(Integer cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }




}


