package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer codigoProducto;
     private EstadoProducto estadoProducto;
     private Linea linea;
     private TipoProducto tipoProducto;
     private String nombreProducto;
     private Date ingresoAlmacenProducto;
     private Date salidaAlmacenProducto;
     private String stockProducto;
     private String preparacionProducto;
     private byte[] fotoProducto;
     private String coloresProducto;
     private String qrProducto;
     private Float pvvProducto;
     private Float pvfProducto;
     private Set<Cuota> cuotas = new HashSet<Cuota>(0);
     private Set<ClienteTienePreferencia> clienteTienePreferencias = new HashSet<ClienteTienePreferencia>(0);
     private Set<ProductoPorPedido> productoPorPedidos = new HashSet<ProductoPorPedido>(0);
     private Set<RecetaProductoTieneInsumo> recetaProductoTieneInsumos = new HashSet<RecetaProductoTieneInsumo>(0);

    public Producto() {
    }

    public Producto(EstadoProducto estadoProducto, Linea linea, TipoProducto tipoProducto, String nombreProducto, Date ingresoAlmacenProducto, Date salidaAlmacenProducto, String stockProducto, String preparacionProducto, byte[] fotoProducto, String coloresProducto, String qrProducto, Float pvvProducto, Float pvfProducto, Set<Cuota> cuotas, Set<ClienteTienePreferencia> clienteTienePreferencias, Set<ProductoPorPedido> productoPorPedidos, Set<RecetaProductoTieneInsumo> recetaProductoTieneInsumos) {
       this.estadoProducto = estadoProducto;
       this.linea = linea;
       this.tipoProducto = tipoProducto;
       this.nombreProducto = nombreProducto;
       this.ingresoAlmacenProducto = ingresoAlmacenProducto;
       this.salidaAlmacenProducto = salidaAlmacenProducto;
       this.stockProducto = stockProducto;
       this.preparacionProducto = preparacionProducto;
       this.fotoProducto = fotoProducto;
       this.coloresProducto = coloresProducto;
       this.qrProducto = qrProducto;
       this.pvvProducto = pvvProducto;
       this.pvfProducto = pvfProducto;
       this.cuotas = cuotas;
       this.clienteTienePreferencias = clienteTienePreferencias;
       this.productoPorPedidos = productoPorPedidos;
       this.recetaProductoTieneInsumos = recetaProductoTieneInsumos;
    }
   
    public Integer getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(Integer codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public EstadoProducto getEstadoProducto() {
        return this.estadoProducto;
    }
    
    public void setEstadoProducto(EstadoProducto estadoProducto) {
        this.estadoProducto = estadoProducto;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }
    public TipoProducto getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Date getIngresoAlmacenProducto() {
        return this.ingresoAlmacenProducto;
    }
    
    public void setIngresoAlmacenProducto(Date ingresoAlmacenProducto) {
        this.ingresoAlmacenProducto = ingresoAlmacenProducto;
    }
    public Date getSalidaAlmacenProducto() {
        return this.salidaAlmacenProducto;
    }
    
    public void setSalidaAlmacenProducto(Date salidaAlmacenProducto) {
        this.salidaAlmacenProducto = salidaAlmacenProducto;
    }
    public String getStockProducto() {
        return this.stockProducto;
    }
    
    public void setStockProducto(String stockProducto) {
        this.stockProducto = stockProducto;
    }
    public String getPreparacionProducto() {
        return this.preparacionProducto;
    }
    
    public void setPreparacionProducto(String preparacionProducto) {
        this.preparacionProducto = preparacionProducto;
    }
    public byte[] getFotoProducto() {
        return this.fotoProducto;
    }
    
    public void setFotoProducto(byte[] fotoProducto) {
        this.fotoProducto = fotoProducto;
    }
    public String getColoresProducto() {
        return this.coloresProducto;
    }
    
    public void setColoresProducto(String coloresProducto) {
        this.coloresProducto = coloresProducto;
    }
    public String getQrProducto() {
        return this.qrProducto;
    }
    
    public void setQrProducto(String qrProducto) {
        this.qrProducto = qrProducto;
    }
    public Float getPvvProducto() {
        return this.pvvProducto;
    }
    
    public void setPvvProducto(Float pvvProducto) {
        this.pvvProducto = pvvProducto;
    }
    public Float getPvfProducto() {
        return this.pvfProducto;
    }
    
    public void setPvfProducto(Float pvfProducto) {
        this.pvfProducto = pvfProducto;
    }
    public Set<Cuota> getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(Set<Cuota> cuotas) {
        this.cuotas = cuotas;
    }
    public Set<ClienteTienePreferencia> getClienteTienePreferencias() {
        return this.clienteTienePreferencias;
    }
    
    public void setClienteTienePreferencias(Set<ClienteTienePreferencia> clienteTienePreferencias) {
        this.clienteTienePreferencias = clienteTienePreferencias;
    }
    public Set<ProductoPorPedido> getProductoPorPedidos() {
        return this.productoPorPedidos;
    }
    
    public void setProductoPorPedidos(Set<ProductoPorPedido> productoPorPedidos) {
        this.productoPorPedidos = productoPorPedidos;
    }
    public Set<RecetaProductoTieneInsumo> getRecetaProductoTieneInsumos() {
        return this.recetaProductoTieneInsumos;
    }
    
    public void setRecetaProductoTieneInsumos(Set<RecetaProductoTieneInsumo> recetaProductoTieneInsumos) {
        this.recetaProductoTieneInsumos = recetaProductoTieneInsumos;
    }




}


