package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PromocionVenta generated by hbm2java
 */
public class PromocionVenta  implements java.io.Serializable {


     private Integer codigoPromocionVenta;
     private Integer cantidadSkuPedido;
     private Float descuentoSkuPedido;
     private Date fechaInicioPromocion;
     private Date fechaExpiracionPromocion;
     private String descripcionPromocion;
     private Set<ClienteTienePedido> clienteTienePedidos = new HashSet<ClienteTienePedido>(0);

    public PromocionVenta() {
    }

    public PromocionVenta(Integer cantidadSkuPedido, Float descuentoSkuPedido, Date fechaInicioPromocion, Date fechaExpiracionPromocion, String descripcionPromocion, Set<ClienteTienePedido> clienteTienePedidos) {
       this.cantidadSkuPedido = cantidadSkuPedido;
       this.descuentoSkuPedido = descuentoSkuPedido;
       this.fechaInicioPromocion = fechaInicioPromocion;
       this.fechaExpiracionPromocion = fechaExpiracionPromocion;
       this.descripcionPromocion = descripcionPromocion;
       this.clienteTienePedidos = clienteTienePedidos;
    }
   
    public Integer getCodigoPromocionVenta() {
        return this.codigoPromocionVenta;
    }
    
    public void setCodigoPromocionVenta(Integer codigoPromocionVenta) {
        this.codigoPromocionVenta = codigoPromocionVenta;
    }
    public Integer getCantidadSkuPedido() {
        return this.cantidadSkuPedido;
    }
    
    public void setCantidadSkuPedido(Integer cantidadSkuPedido) {
        this.cantidadSkuPedido = cantidadSkuPedido;
    }
    public Float getDescuentoSkuPedido() {
        return this.descuentoSkuPedido;
    }
    
    public void setDescuentoSkuPedido(Float descuentoSkuPedido) {
        this.descuentoSkuPedido = descuentoSkuPedido;
    }
    public Date getFechaInicioPromocion() {
        return this.fechaInicioPromocion;
    }
    
    public void setFechaInicioPromocion(Date fechaInicioPromocion) {
        this.fechaInicioPromocion = fechaInicioPromocion;
    }
    public Date getFechaExpiracionPromocion() {
        return this.fechaExpiracionPromocion;
    }
    
    public void setFechaExpiracionPromocion(Date fechaExpiracionPromocion) {
        this.fechaExpiracionPromocion = fechaExpiracionPromocion;
    }
    public String getDescripcionPromocion() {
        return this.descripcionPromocion;
    }
    
    public void setDescripcionPromocion(String descripcionPromocion) {
        this.descripcionPromocion = descripcionPromocion;
    }
    public Set<ClienteTienePedido> getClienteTienePedidos() {
        return this.clienteTienePedidos;
    }
    
    public void setClienteTienePedidos(Set<ClienteTienePedido> clienteTienePedidos) {
        this.clienteTienePedidos = clienteTienePedidos;
    }




}


