package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private Integer codigoProvincia;
     private Pais pais;
     private String nombreProvincia;
     private Set<Ciudad> ciudads = new HashSet<Ciudad>(0);

    public Provincia() {
    }

    public Provincia(Pais pais, String nombreProvincia, Set<Ciudad> ciudads) {
       this.pais = pais;
       this.nombreProvincia = nombreProvincia;
       this.ciudads = ciudads;
    }
   
    public Integer getCodigoProvincia() {
        return this.codigoProvincia;
    }
    
    public void setCodigoProvincia(Integer codigoProvincia) {
        this.codigoProvincia = codigoProvincia;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombreProvincia() {
        return this.nombreProvincia;
    }
    
    public void setNombreProvincia(String nombreProvincia) {
        this.nombreProvincia = nombreProvincia;
    }
    public Set<Ciudad> getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set<Ciudad> ciudads) {
        this.ciudads = ciudads;
    }




}


