package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReceProduTiInsumo generated by hbm2java
 */
public class ReceProduTiInsumo  implements java.io.Serializable {


     private Integer codigoReceProduTiInsumo;
     private Date version;
     private Insumo insumo;
     private Producto producto;
     private RecetaProducto recetaProducto;
     private Float cantidadUsada;
     private Date fechaCreacion;
     private String descripcion;
     private Float temperaturaHorno;
     private Float temperaturaReposo;
     private Float dimensionAltura;
     private Float dimensionAnchura;
     private Float dimensionEspesor;
     private Float dimensionProfundidad;
     private Float porcentajeEnProducto;

    public ReceProduTiInsumo() {
    }

    public ReceProduTiInsumo(Insumo insumo, Producto producto, RecetaProducto recetaProducto, Float cantidadUsada, Date fechaCreacion, String descripcion, Float temperaturaHorno, Float temperaturaReposo, Float dimensionAltura, Float dimensionAnchura, Float dimensionEspesor, Float dimensionProfundidad, Float porcentajeEnProducto) {
       this.insumo = insumo;
       this.producto = producto;
       this.recetaProducto = recetaProducto;
       this.cantidadUsada = cantidadUsada;
       this.fechaCreacion = fechaCreacion;
       this.descripcion = descripcion;
       this.temperaturaHorno = temperaturaHorno;
       this.temperaturaReposo = temperaturaReposo;
       this.dimensionAltura = dimensionAltura;
       this.dimensionAnchura = dimensionAnchura;
       this.dimensionEspesor = dimensionEspesor;
       this.dimensionProfundidad = dimensionProfundidad;
       this.porcentajeEnProducto = porcentajeEnProducto;
    }
   
    public Integer getCodigoReceProduTiInsumo() {
        return this.codigoReceProduTiInsumo;
    }
    
    public void setCodigoReceProduTiInsumo(Integer codigoReceProduTiInsumo) {
        this.codigoReceProduTiInsumo = codigoReceProduTiInsumo;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public Insumo getInsumo() {
        return this.insumo;
    }
    
    public void setInsumo(Insumo insumo) {
        this.insumo = insumo;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public RecetaProducto getRecetaProducto() {
        return this.recetaProducto;
    }
    
    public void setRecetaProducto(RecetaProducto recetaProducto) {
        this.recetaProducto = recetaProducto;
    }
    public Float getCantidadUsada() {
        return this.cantidadUsada;
    }
    
    public void setCantidadUsada(Float cantidadUsada) {
        this.cantidadUsada = cantidadUsada;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Float getTemperaturaHorno() {
        return this.temperaturaHorno;
    }
    
    public void setTemperaturaHorno(Float temperaturaHorno) {
        this.temperaturaHorno = temperaturaHorno;
    }
    public Float getTemperaturaReposo() {
        return this.temperaturaReposo;
    }
    
    public void setTemperaturaReposo(Float temperaturaReposo) {
        this.temperaturaReposo = temperaturaReposo;
    }
    public Float getDimensionAltura() {
        return this.dimensionAltura;
    }
    
    public void setDimensionAltura(Float dimensionAltura) {
        this.dimensionAltura = dimensionAltura;
    }
    public Float getDimensionAnchura() {
        return this.dimensionAnchura;
    }
    
    public void setDimensionAnchura(Float dimensionAnchura) {
        this.dimensionAnchura = dimensionAnchura;
    }
    public Float getDimensionEspesor() {
        return this.dimensionEspesor;
    }
    
    public void setDimensionEspesor(Float dimensionEspesor) {
        this.dimensionEspesor = dimensionEspesor;
    }
    public Float getDimensionProfundidad() {
        return this.dimensionProfundidad;
    }
    
    public void setDimensionProfundidad(Float dimensionProfundidad) {
        this.dimensionProfundidad = dimensionProfundidad;
    }
    public Float getPorcentajeEnProducto() {
        return this.porcentajeEnProducto;
    }
    
    public void setPorcentajeEnProducto(Float porcentajeEnProducto) {
        this.porcentajeEnProducto = porcentajeEnProducto;
    }




}


