package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RecetaProducto generated by hbm2java
 */
public class RecetaProducto  implements java.io.Serializable {


     private Integer codigoRecetaProducto;
     private String modeloRecetaProducto;
     private Date fechaCreacionRecetaProducto;
     private Set<RecetaProductoTieneInsumo> recetaProductoTieneInsumos = new HashSet<RecetaProductoTieneInsumo>(0);

    public RecetaProducto() {
    }

    public RecetaProducto(String modeloRecetaProducto, Date fechaCreacionRecetaProducto, Set<RecetaProductoTieneInsumo> recetaProductoTieneInsumos) {
       this.modeloRecetaProducto = modeloRecetaProducto;
       this.fechaCreacionRecetaProducto = fechaCreacionRecetaProducto;
       this.recetaProductoTieneInsumos = recetaProductoTieneInsumos;
    }
   
    public Integer getCodigoRecetaProducto() {
        return this.codigoRecetaProducto;
    }
    
    public void setCodigoRecetaProducto(Integer codigoRecetaProducto) {
        this.codigoRecetaProducto = codigoRecetaProducto;
    }
    public String getModeloRecetaProducto() {
        return this.modeloRecetaProducto;
    }
    
    public void setModeloRecetaProducto(String modeloRecetaProducto) {
        this.modeloRecetaProducto = modeloRecetaProducto;
    }
    public Date getFechaCreacionRecetaProducto() {
        return this.fechaCreacionRecetaProducto;
    }
    
    public void setFechaCreacionRecetaProducto(Date fechaCreacionRecetaProducto) {
        this.fechaCreacionRecetaProducto = fechaCreacionRecetaProducto;
    }
    public Set<RecetaProductoTieneInsumo> getRecetaProductoTieneInsumos() {
        return this.recetaProductoTieneInsumos;
    }
    
    public void setRecetaProductoTieneInsumos(Set<RecetaProductoTieneInsumo> recetaProductoTieneInsumos) {
        this.recetaProductoTieneInsumos = recetaProductoTieneInsumos;
    }




}


