package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1



/**
 * RecetaProductoTieneInsumo generated by hbm2java
 */
public class RecetaProductoTieneInsumo  implements java.io.Serializable {


     private Integer codigoRecetaProductoTieneInsumo;
     private Insumo insumo;
     private Producto producto;
     private RecetaProducto recetaProducto;

    public RecetaProductoTieneInsumo() {
    }

    public RecetaProductoTieneInsumo(Insumo insumo, Producto producto, RecetaProducto recetaProducto) {
       this.insumo = insumo;
       this.producto = producto;
       this.recetaProducto = recetaProducto;
    }
   
    public Integer getCodigoRecetaProductoTieneInsumo() {
        return this.codigoRecetaProductoTieneInsumo;
    }
    
    public void setCodigoRecetaProductoTieneInsumo(Integer codigoRecetaProductoTieneInsumo) {
        this.codigoRecetaProductoTieneInsumo = codigoRecetaProductoTieneInsumo;
    }
    public Insumo getInsumo() {
        return this.insumo;
    }
    
    public void setInsumo(Insumo insumo) {
        this.insumo = insumo;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public RecetaProducto getRecetaProducto() {
        return this.recetaProducto;
    }
    
    public void setRecetaProducto(RecetaProducto recetaProducto) {
        this.recetaProducto = recetaProducto;
    }




}


