package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoImpuesto generated by hbm2java
 */
public class TipoImpuesto  implements java.io.Serializable {


     private Integer codigoTipoImpuesto;
     private Date version;
     private String nombreTipoImpuesto;
     private Float porcentajeTipoImpuesto;
     private Set<IgvVenta> igvVentas = new HashSet<IgvVenta>(0);

    public TipoImpuesto() {
    }

    public TipoImpuesto(String nombreTipoImpuesto, Float porcentajeTipoImpuesto, Set<IgvVenta> igvVentas) {
       this.nombreTipoImpuesto = nombreTipoImpuesto;
       this.porcentajeTipoImpuesto = porcentajeTipoImpuesto;
       this.igvVentas = igvVentas;
    }
   
    public Integer getCodigoTipoImpuesto() {
        return this.codigoTipoImpuesto;
    }
    
    public void setCodigoTipoImpuesto(Integer codigoTipoImpuesto) {
        this.codigoTipoImpuesto = codigoTipoImpuesto;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public String getNombreTipoImpuesto() {
        return this.nombreTipoImpuesto;
    }
    
    public void setNombreTipoImpuesto(String nombreTipoImpuesto) {
        this.nombreTipoImpuesto = nombreTipoImpuesto;
    }
    public Float getPorcentajeTipoImpuesto() {
        return this.porcentajeTipoImpuesto;
    }
    
    public void setPorcentajeTipoImpuesto(Float porcentajeTipoImpuesto) {
        this.porcentajeTipoImpuesto = porcentajeTipoImpuesto;
    }
    public Set<IgvVenta> getIgvVentas() {
        return this.igvVentas;
    }
    
    public void setIgvVentas(Set<IgvVenta> igvVentas) {
        this.igvVentas = igvVentas;
    }




}


