package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoProducto generated by hbm2java
 */
public class TipoProducto  implements java.io.Serializable {


     private Integer codigoTipoProducto;
     private String nombreTipoProducto;
     private Float tiempoenhornoTipoProducto;
     private Float temperaturaenhornoTipoProducto;
     private byte[] fotoTipoProducto;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TipoProducto() {
    }

    public TipoProducto(String nombreTipoProducto, Float tiempoenhornoTipoProducto, Float temperaturaenhornoTipoProducto, byte[] fotoTipoProducto, Set<Producto> productos) {
       this.nombreTipoProducto = nombreTipoProducto;
       this.tiempoenhornoTipoProducto = tiempoenhornoTipoProducto;
       this.temperaturaenhornoTipoProducto = temperaturaenhornoTipoProducto;
       this.fotoTipoProducto = fotoTipoProducto;
       this.productos = productos;
    }
   
    public Integer getCodigoTipoProducto() {
        return this.codigoTipoProducto;
    }
    
    public void setCodigoTipoProducto(Integer codigoTipoProducto) {
        this.codigoTipoProducto = codigoTipoProducto;
    }
    public String getNombreTipoProducto() {
        return this.nombreTipoProducto;
    }
    
    public void setNombreTipoProducto(String nombreTipoProducto) {
        this.nombreTipoProducto = nombreTipoProducto;
    }
    public Float getTiempoenhornoTipoProducto() {
        return this.tiempoenhornoTipoProducto;
    }
    
    public void setTiempoenhornoTipoProducto(Float tiempoenhornoTipoProducto) {
        this.tiempoenhornoTipoProducto = tiempoenhornoTipoProducto;
    }
    public Float getTemperaturaenhornoTipoProducto() {
        return this.temperaturaenhornoTipoProducto;
    }
    
    public void setTemperaturaenhornoTipoProducto(Float temperaturaenhornoTipoProducto) {
        this.temperaturaenhornoTipoProducto = temperaturaenhornoTipoProducto;
    }
    public byte[] getFotoTipoProducto() {
        return this.fotoTipoProducto;
    }
    
    public void setFotoTipoProducto(byte[] fotoTipoProducto) {
        this.fotoTipoProducto = fotoTipoProducto;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


