package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoInsumo generated by hbm2java
 */
public class TipoInsumo  implements java.io.Serializable {


     private Integer codigoTipoInsumo;
     private Date version;
     private String nombreTipoInsumo;
     private Set<Insumo> insumos = new HashSet<Insumo>(0);

    public TipoInsumo() {
    }

    public TipoInsumo(String nombreTipoInsumo, Set<Insumo> insumos) {
       this.nombreTipoInsumo = nombreTipoInsumo;
       this.insumos = insumos;
    }
   
    public Integer getCodigoTipoInsumo() {
        return this.codigoTipoInsumo;
    }
    
    public void setCodigoTipoInsumo(Integer codigoTipoInsumo) {
        this.codigoTipoInsumo = codigoTipoInsumo;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public String getNombreTipoInsumo() {
        return this.nombreTipoInsumo;
    }
    
    public void setNombreTipoInsumo(String nombreTipoInsumo) {
        this.nombreTipoInsumo = nombreTipoInsumo;
    }
    public Set<Insumo> getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Set<Insumo> insumos) {
        this.insumos = insumos;
    }




}


