package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer codigoUsuario;
     private Distrito distrito;
     private EstadoUsuario estadoUsuario;
     private TipoUsuario tipoUsuario;
     private String nombreUsuario;
     private String apellidoUsuario;
     private Date fechaNacimientoUsuario;
     private String direccionUsuario;
     private String nombreLogeoUsuario;
     private String passwordUsuario;
     private byte[] fotoUsuario;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Vendedor> vendedors = new HashSet<Vendedor>(0);

    public Usuario() {
    }

    public Usuario(Distrito distrito, EstadoUsuario estadoUsuario, TipoUsuario tipoUsuario, String nombreUsuario, String apellidoUsuario, Date fechaNacimientoUsuario, String direccionUsuario, String nombreLogeoUsuario, String passwordUsuario, byte[] fotoUsuario, Set<Cliente> clientes, Set<Vendedor> vendedors) {
       this.distrito = distrito;
       this.estadoUsuario = estadoUsuario;
       this.tipoUsuario = tipoUsuario;
       this.nombreUsuario = nombreUsuario;
       this.apellidoUsuario = apellidoUsuario;
       this.fechaNacimientoUsuario = fechaNacimientoUsuario;
       this.direccionUsuario = direccionUsuario;
       this.nombreLogeoUsuario = nombreLogeoUsuario;
       this.passwordUsuario = passwordUsuario;
       this.fotoUsuario = fotoUsuario;
       this.clientes = clientes;
       this.vendedors = vendedors;
    }
   
    public Integer getCodigoUsuario() {
        return this.codigoUsuario;
    }
    
    public void setCodigoUsuario(Integer codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }
    public EstadoUsuario getEstadoUsuario() {
        return this.estadoUsuario;
    }
    
    public void setEstadoUsuario(EstadoUsuario estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getApellidoUsuario() {
        return this.apellidoUsuario;
    }
    
    public void setApellidoUsuario(String apellidoUsuario) {
        this.apellidoUsuario = apellidoUsuario;
    }
    public Date getFechaNacimientoUsuario() {
        return this.fechaNacimientoUsuario;
    }
    
    public void setFechaNacimientoUsuario(Date fechaNacimientoUsuario) {
        this.fechaNacimientoUsuario = fechaNacimientoUsuario;
    }
    public String getDireccionUsuario() {
        return this.direccionUsuario;
    }
    
    public void setDireccionUsuario(String direccionUsuario) {
        this.direccionUsuario = direccionUsuario;
    }
    public String getNombreLogeoUsuario() {
        return this.nombreLogeoUsuario;
    }
    
    public void setNombreLogeoUsuario(String nombreLogeoUsuario) {
        this.nombreLogeoUsuario = nombreLogeoUsuario;
    }
    public String getPasswordUsuario() {
        return this.passwordUsuario;
    }
    
    public void setPasswordUsuario(String passwordUsuario) {
        this.passwordUsuario = passwordUsuario;
    }
    public byte[] getFotoUsuario() {
        return this.fotoUsuario;
    }
    
    public void setFotoUsuario(byte[] fotoUsuario) {
        this.fotoUsuario = fotoUsuario;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<Vendedor> getVendedors() {
        return this.vendedors;
    }
    
    public void setVendedors(Set<Vendedor> vendedors) {
        this.vendedors = vendedors;
    }




}


