package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private Integer codigoVendedor;
     private Date version;
     private Area area;
     private Usuario usuario;
     private String codigoVentaVendedor;
     private Set<ClienteTienePedido> clienteTienePedidos = new HashSet<ClienteTienePedido>(0);

    public Vendedor() {
    }

    public Vendedor(Area area, Usuario usuario, String codigoVentaVendedor, Set<ClienteTienePedido> clienteTienePedidos) {
       this.area = area;
       this.usuario = usuario;
       this.codigoVentaVendedor = codigoVentaVendedor;
       this.clienteTienePedidos = clienteTienePedidos;
    }
   
    public Integer getCodigoVendedor() {
        return this.codigoVendedor;
    }
    
    public void setCodigoVendedor(Integer codigoVendedor) {
        this.codigoVendedor = codigoVendedor;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCodigoVentaVendedor() {
        return this.codigoVentaVendedor;
    }
    
    public void setCodigoVentaVendedor(String codigoVentaVendedor) {
        this.codigoVentaVendedor = codigoVentaVendedor;
    }
    public Set<ClienteTienePedido> getClienteTienePedidos() {
        return this.clienteTienePedidos;
    }
    
    public void setClienteTienePedidos(Set<ClienteTienePedido> clienteTienePedidos) {
        this.clienteTienePedidos = clienteTienePedidos;
    }




}


