package com.pojos;
// Generated Apr 27, 2018 1:46:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ZonaTieneDistrito generated by hbm2java
 */
public class ZonaTieneDistrito  implements java.io.Serializable {


     private Integer codigoZonaTieneDistrito;
     private Distrito distrito;
     private Zona zona;
     private Set<CplTieneZtd> cplTieneZtds = new HashSet<CplTieneZtd>(0);

    public ZonaTieneDistrito() {
    }

    public ZonaTieneDistrito(Distrito distrito, Zona zona, Set<CplTieneZtd> cplTieneZtds) {
       this.distrito = distrito;
       this.zona = zona;
       this.cplTieneZtds = cplTieneZtds;
    }
   
    public Integer getCodigoZonaTieneDistrito() {
        return this.codigoZonaTieneDistrito;
    }
    
    public void setCodigoZonaTieneDistrito(Integer codigoZonaTieneDistrito) {
        this.codigoZonaTieneDistrito = codigoZonaTieneDistrito;
    }
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }
    public Zona getZona() {
        return this.zona;
    }
    
    public void setZona(Zona zona) {
        this.zona = zona;
    }
    public Set<CplTieneZtd> getCplTieneZtds() {
        return this.cplTieneZtds;
    }
    
    public void setCplTieneZtds(Set<CplTieneZtd> cplTieneZtds) {
        this.cplTieneZtds = cplTieneZtds;
    }




}


