package com.pojos;
// Generated May 31, 2018 6:38:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Zona generated by hbm2java
 */
public class Zona  implements java.io.Serializable {


     private Integer codigoZona;
     private Date version;
     private String nombreZona;
     private Set<ZonaTieneDistrito> zonaTieneDistritos = new HashSet<ZonaTieneDistrito>(0);

    public Zona() {
    }

    public Zona(String nombreZona, Set<ZonaTieneDistrito> zonaTieneDistritos) {
       this.nombreZona = nombreZona;
       this.zonaTieneDistritos = zonaTieneDistritos;
    }
   
    public Integer getCodigoZona() {
        return this.codigoZona;
    }
    
    public void setCodigoZona(Integer codigoZona) {
        this.codigoZona = codigoZona;
    }
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }
    public String getNombreZona() {
        return this.nombreZona;
    }
    
    public void setNombreZona(String nombreZona) {
        this.nombreZona = nombreZona;
    }
    public Set<ZonaTieneDistrito> getZonaTieneDistritos() {
        return this.zonaTieneDistritos;
    }
    
    public void setZonaTieneDistritos(Set<ZonaTieneDistrito> zonaTieneDistritos) {
        this.zonaTieneDistritos = zonaTieneDistritos;
    }




}


